### DISCUSSION TITLE
How to only run build on PR?

### DISCUSSION THREAD

**Discussion by littleGnAl** [cirruslabs/cirrus-ci-docs#1148] [Q&A]
I want to run the build on PR only and filter specific base branches as my github action does:
```
on:
  pull_request:
    branches: 
      - main
      - release/**
      - special/**
      - dev/**
```

I tried to add `only_if` expression to strict the build to run on PR only, but it seems not to work correctly, the PR skipped but with the correct config. Here's my implementation, can you help me check the logic? 
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/0d13ec68f1f8198c26ebc24be2ad4213da2b1dd8/.cirrus.yml#L7
