### DISCUSSION TITLE
No images found for FreeBSD 14.0

### DISCUSSION THREAD

**Discussion by Minoru** [cirruslabs/cirrus-ci-docs#1256] [Q&A] [answered]
[FreeBSD 14.0 came out a month ago](https://www.freebsd.org/releases/14.0R/announce/), complete with a freebsd-org-cloud-dev/freebsd-14-0-release-amd64 image on Google Compute Engine. However, the following config fails:

```yaml
task:
    matrix:
        - name: FreeBSD 14.0
          freebsd_instance:
            image: freebsd-14-0-release-amd64
            cpu: 4
            memory: 8GB
```

with the following error:

```
Failed to start an instance: INVALID_ARGUMENT: Bad Request 400 Bad Request POST https://compute.googleapis.com:443/compute/v1/projects/cirrus-ci-community/zones/us-central1-c/instances { "error": { "code": 400, "message": "Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'projects/freebsd-org-cloud-dev/global/images/freebsd-14-0-release-amd64'. The referenced image resource cannot be found.", "errors": [ { "message": "Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'projects/freebsd-org-cloud-dev/global/images/freebsd-14-0-release-amd64'. The referenced image resource cannot be found.", "domain": "global", "reason": "invalid" } ] } } 
```

(https://cirrus-ci.com/task/5992006774685696)

Ditto for `freebsd-14-0` (https://cirrus-ci.com/build/5289287311163392) and `freebsd-14-0-snap` (https://cirrus-ci.com/build/5713877241954304), even though the latter is documented in Cirrus docs at https://cirrus-ci.org/guide/FreeBSD/#list-of-available-image-families

I don't have an account with Google Cloud Compute, and can't run the provided command to find out which images are available. Anyone got any pointers?
