### DISCUSSION TITLE
Does `folder`/`folders`  inside `cache` support env vars?

### DISCUSSION THREAD

**Discussion by abravalheri** [cirruslabs/cirrus-ci-docs#1264] [Q&A] [answered]
Hello, I was wondering if I can use an environment variable to pass the value of `folder` inside of a cache instruction. Something like the following:

```yaml
env:
  TOOLXYZ_CACHE: ${HOME}/.cache/toolxyz

prepare_task:
  # ...
  test_files_cache:
    folder: ${TOOLXYZ_CACHE}
    populate_script: ./my_populate_script
    fingerprint_script: echo $CIRRUS_BUILD_ID
    reupload_on_changes: true
  # ...
```

Does anyone know if something like the above is supported? Or is there an alternative for that which keeps a single source of truth for the value of the environment variable. Also would the `folder: ${ENV_VAR}` syntax be supported independently of the OS used in the task?
