### DISCUSSION TITLE
how to configure to run whole cirrus.yml tasks on master only (no executions on PRs)

### DISCUSSION THREAD

**Discussion by romani** [cirruslabs/cirrus-ci-docs#1269] [Q&A] [answered]
We want to not run cirrus in PRs as free quota is quickly exceeded. And we have bunch of PRs.
How to run only on master updated ? after merge of PR.
To make sure cirrus is not even visible in PR CIs.

**Comment by fkorotkov** [comment, marked as answer]
You can put the following `only_if` statement in your `.cirrus.yml`:

```yaml
# .cirrus.yml

only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH

task1:
  ...

task2:
  ...
```

This way you'll pnly run tasks on the default branch (either `master` or `main` depending on your settings).
