### DISCUSSION TITLE
Tips and tricks on improving windows tasks boot up times

### DISCUSSION THREAD

**Discussion by ericoporto** [cirruslabs/cirrus-ci-docs#1297] [Q&A]
While it seems Linux and macOS tasks run very fast, Windows containers seem to take a loooong time. Are there any tips and tricks to get them to run faster?

Unfortunately I need MS Visual Studio, CPP, C++/CLI and .NET Framework stuff and all this stuff will add to a reasonable size in the image.

**Comment by edigaryev** [comment]
You can [configure EKS](https://cirrus-ci.org/guide/supported-computing-services/#eks) and run Windows containers there. Here's an example Cirrus CI configuration:

```yaml
aws_credentials: [...]

task:
  eks_container:
    image: cirrusci/windowsservercore:2019
    cluster_name: my-cluster
    region: us-east-1
    namespace: default
    platform: windows
    cpu: 1
    memory: 1

  build_script:
    - Write-Host 'Hello, World!'

env:
  CIRRUS_OS: windows
  CIRRUS_SHELL: powershell
```

They should be faster to start once the OC image gets cached on the Kubernetes node(s).
