### DISCUSSION TITLE
html reports

### DISCUSSION THREAD

**Discussion by vinferrer** [cirruslabs/cirrus-ci-docs#790] [Q&A]
Hi,

Is there a way to output html reports as artifacts that we can directly see in the browser like this one:

https://12772-110845855-gh.circle-artifacts.com/0/tmp/data/five-echo/TED.five-echo-manual/tedana_report.html

**Comment by fkorotkov** [comment]
@vinferrer actually you can if you put `text/html` as your artifact's [`type`](https://cirrus-ci.org/guide/writing-tasks/#artifact-type).

**Reply by RDIL** [reply]
Oh yeah, I thought he meant a report of the build's info as a whole.

**Reply by vinferrer** [reply]
```
Build_docs_task:
  depends_on:
  - makeenv
  env:
    PYTHON: 3.9
  environment_cache:
    folder: conda-env
    fingerprint_script:
      - echo $PYTHON
      - cat setup.py
    populate_script:
      - source activate $PWD/conda-env
  Build_documentation_script:
  - apt-get install -y make tar
  - source activate $PWD/conda-env
  - make -C docs html
  docs_artifacts:
    path: "/tmp/cirrus-ci-build/docs/_build/html"
    type: text/html
```
I think i have a problem with the path, I am pointing to the folder, should I point to an specific html? It is a docs build, so there are many pages
