### DISCUSSION TITLE
Uploading artifact on failure

### DISCUSSION THREAD

**Discussion by evertonlperes** [cirruslabs/cirrus-ci-docs#946] [Q&A] [answered]
Hi there,
I was wondering to ask if there's a way to upload an artifact (zip) when the previous step has failed.
On Cirrus CI looks like the artifact will only be uploaded with the previous step has passed.

Is there a way to include something like:
```yaml
build_and_test_task:
  binaries_artifacts:
   on_failure: true
   path: "screenshots/*"
   format: zip
```
Just looking for some opportunities to upload some screenshots results from the cirrus runner.

Thanks!

**Comment by fkorotkov** [comment]
Hey @evertonlperes, you can do it already with [execution behaviour feature](https://cirrus-ci.org/guide/writing-tasks/#execution-behavior-of-instructions). Just wrap your `artifacts` instruction in `on_failure` or even `always`:

```yaml
on_failure:
  binaries_artifacts:
     path: "screenshots/*"
     format: zip
```

**Reply by evertonlperes** [reply]
awesome @fkorotkov 
I'll give a try, thanks for helping!

**Reply by evertonlperes** [reply]
No luck :( @fkorotkov 
It could be some mistake from my side, but I didn't get the artifact upload working.
The file has been created properly but still not uploading it to the UI, returning:
`Uploading 0 artifacts for /tmp/cirrus-ci-build/home/ranchertest/pw-log.txt`

I did some changes and tried to upload all the files from a report folder, same thing... it does not upload the files.
`Uploading 0 artifacts for /tmp/cirrus-ci-build/home/ranchertest/e2e/reports/**`

```yaml
  always:
    pwtrace_artifacts:
      path: "home/ranchertest/e2e/reports/**"
```

Here's a snippet from my workflow:

```yaml
      # Tests should run as non-root user - setting up a test user
      prepate_user_script: |
        groupadd -g $(stat -c '%g' /dev/kvm) kvm
        useradd -m -G kvm ranchertest
        cp -rf . /home/ranchertest
      build_script: |
        chown -R ranchertest:ranchertest /home/ranchertest
        chown -R ranchertest:ranchertest /dev/kvm
        sudo -iu ranchertest DEBUG=pw:install npm install
        sudo -iu ranchertest npx playwright install-deps
      test_script: |
        export KUBECONFIG=/home/ranchertest/.kube/config
        sudo -iu ranchertest CI=1 DEBUG=pw* DEBUG_FILE=pw-log.txt xvfb-run --auto-servernum -- npm run test:e2e
  always:
    pwtrace_artifacts:
      path: "home/ranchertest/pw-log.txt"
      type: text/plain
      format: txt
```
I might missing something though, first time setting up Cirrus :)

**Reply by fkorotkov** [reply]
Can you share a link to your build? I'll try to re-run with a [terminal](https://medium.com/cirruslabs/introducing-cirrus-terminal-a-simple-way-to-get-ssh-like-access-to-your-tasks-1def0449065d) to see what's going on there.

**Reply by evertonlperes** [reply]
Sure thing. Here we go: https://cirrus-ci.com/task/5550026899324928?logs=test#L48

**Reply by fkorotkov** [reply]
I think this might be the typo(you need to use an absolute path): https://github.com/evertonlperes/rancher-desktop/pull/10/files#r766653211

**Reply by evertonlperes** [reply]
That's weird, even with the absolute path, still getting the same behaviour though:
`Uploading 0 artifacts for /tmp/cirrus-ci-build/home/ranchertest/pw-log.txt`

And the file wasn't uploaded even though the file exists:
```bash
root@cirrus-task-4661075479101440:/tmp/cirrus-ci-build# ls -la /home/ranchertest/pw-log.txt -rw-rw-r-- 1 ranchertest ranchertest 32850169 Dec 10 16:41 /home/ranchertest/pw-log.txt
```
https://cirrus-ci.com/task/5934862317125632

**Reply by fkorotkov** [reply]
My bad. I just realized and it's actually [stated in the docs](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction):

> Right now only storing files under $CIRRUS_WORKING_DIR folder as artifacts is supported

So you'll have to copy over the file into your working directory and then upload it. It's required for now to figure out relative paths in the resulting archive. I've created https://github.com/cirruslabs/cirrus-ci-agent/issues/197 to support uploading artifacts by arbitrary path.

**Reply by evertonlperes** [reply]
Ough, I just misunderstood the sentence, my bad either.
I thought any file under `$CIRRUS_WORKING_DIR/*` will be uploaded... :P 
I'll create a workaround just to get it working on my stuff and wait to the fix being release. 

Glad that you catch it. Thanks for helping and opening the fix.

**Comment by evertonlperes** [comment, marked as answer]
Closing this by: [cirruslabs/cirrus-ci-agent#197](https://github.com/cirruslabs/cirrus-ci-agent/issues/197)

**Comment by evertonlperes** [comment]
It did the trick moving the artifacts around:
```yaml
  always: # or on_failure:
    custom_script: |
      cp -R /home/ranchertest/e2e/reports/ .
    logs_artifacts:
      path: "/reports/*"
```
On my scenario, I need to run the E2E tests as a non-root user due our project requirements. That's the reason to move the files created as a `non-root` to a `root` environment in order to be uploaded.
