### DISCUSSION TITLE
Cron/Scheduled Tasks

### DISCUSSION THREAD

**Discussion by evertonlperes** [cirruslabs/cirrus-ci-docs#949] [Q&A] [answered]
I was wondering how we can set up a cron job (specific on main branch) and not sure how to configure it. 

Is there a way to setup the cron job like, passing a specific tag, e.g.: `schedule` ?

```yaml
task:
 schedule: 0 7 * * 1-6 <-- like this
  trigger_type: manual
  name: E2E Tests
  timeout_in: 45
  container:
    image: ubuntu:20.04
    kvm: true
  env:
    DEBIAN_FRONTEND: noninteractive
```

Also, I might misunderstood the documentation, but it's not clear the steps to configure the cron builds/tasks in the repository settings.
Should I configure a environment and create the `CIRRUS_CRON` as a secret?

Thanks!

**Comment by evertonlperes** [comment]
Ops.. nvm, just found the repository settings page on cirrus-ci.com :P

**Comment by fkorotkov** [comment, marked as answer]
Here is [documentation around Cron builds](https://cirrus-ci.org/guide/writing-tasks/#cron-builds). There is a useful link to a generator for the cron expressions. 👌

**Reply by evertonlperes** [reply]
@fkorotkov 
Another question :P 
I have a testing scenario that I'd like to keep the workflow as a `manual trigger` and `cron task` enabled.
The current behaviour is:
* The cron will trigger the build on the correct time
* The task won't be trigger automatically
* You need to manually trigger the cron build in order to start the task.

I was wondering if this is the expected behaviour or there's another way to start a cron build task, bypassing the manual trigger.

Examples:
https://cirrus-ci.com/build/5789479486095360
https://cirrus-ci.com/build/5654840784191488
https://cirrus-ci.com/build/5956991196594176

Thanks for helping!

**Reply by fkorotkov** [reply]
It's an expected behavior.

I guess a workaround can be to replace `trigger_type: manual` with:

```
matrix:
  - trigger_type: automatic
    only_if: $CIRRUS_CRON != ''
  - trigger_type: manual
    only_if: $CIRRUS_CRON == ''
```

**Reply by evertonlperes** [reply]
Sweet, thanks @fkorotkov - it works like a charm.

Here's my changes if someone has the same scenario:
```yaml
task:
  matrix:
    # Keep manual trigger for all pushes (prs and merges)
    - trigger_type: manual
      only_if: $CIRRUS_CRON == ''
    # Only trigger task automatically if it's a CRON task and main branch
    - trigger_type: automatic
      only_if: $CIRRUS_CRON != '' && $BRANCH == "main"
  name: XPTO_BUILD
  timeout_in: 60
  container: node:latest
  (...)
```
