### ISSUE TITLE
Expanding VARIABLES in depends_on

### ISSUE THREAD

**Issue by 5u623l20** [cirruslabs/cirrus-ci-docs#1001]
# Description
Any variable name in `depends_on` is not expanded. Here is a small example:

```yaml
build_task:
  name: BUILD-$TARGET_ARCH
  matrix:
    - NAME: ${TARGET_ARCH}
      env:
        TARGET_ARCH: amd64
    - NAME: ${TARGET_ARCH}
      env:
        TARGET_ARCH: i386
  script:
    - echo $TARGET_ARCH

dependss_task:
  name: DEPEND-$TARGET_ARCH
  depends_on: BUILD-$TARGET_ARCH
  matrix:
    - NAME: ${TARGET_ARCH}
      env:
        TARGET_ARCH: amd64
    - NAME: ${TARGET_ARCH}
      env:
        TARGET_ARCH: i386
  script:
    - echo "This task is dependent upon BUILD-${TARGET_ARCH}"
```

This errors out with ***Error while parsing tasks: INVALID_ARGUMENT: parsing error: there's no task 'BUILD-$TARGET_ARCH', but task 'DEPEND-amd64' depends on it!***

# Context
This would really help expanding dependency works. There is an `alias` option but that will wait for all the tasks of the `build` matrix to finish before moving on.
