### ISSUE TITLE
docker_builder for Windows doesn't have Python?

### ISSUE THREAD

**Issue by jack1142** [cirruslabs/cirrus-ci-docs#1033]
## Expected Behavior

I expected that this task will succeed:
```yaml
docker_builder:
  platform: windows
  os_version: "2019"
  script: python --version
```
The documentation says that Docker Builder has Python pre-installed:
https://cirrus-ci.org/guide/docker-builder-vm/#pre-installed-packages

## Real Behavior

The task failed.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Windows Docker Builder
  - Task name: main
  - Script/cache name (if applies): main
https://cirrus-ci.com/task/5506087917977600
