### ISSUE TITLE
Where is the error "task has no instance attached" explained?

### ISSUE THREAD

**Issue by guyharris** [cirruslabs/cirrus-ci-docs#1043]
## Expected Behavior

I could find an explanation of what "task has no instance attached" and, ideally, how to get an "instance" attached to a task.

## Real Behavior

I couldn't find anything if I did a Google search for the quoted string "task has no instance attached" - searching not just the Cirrus CI sites, but *anything else Google indexes*.

# Related Info

This is a (tick one of the following):

- [x ] Website issue
  - Link to page: if there were a page discussing this, I'd link to it, but....

This all started when I added the tiny test task

```
windows_task:
    name: windows-amd64
    only_if: $CIRRUS_BRANCH != 'coverity_scan'
    windows_contaainer:
        image: cirrusci/windowsservercore:2019
    script:
        - set
```

to [libpcap's .cirrus.yml](https://github.com/the-tcpdump-group/libpcap/blob/master/.cirrus.yml), where the intent was to see what the environment was set to, so that I'd know what had to be tweaked in order to set up a build environment - and to see whether this all worked.

I got the error in question, and could not find a clue anywhere as to how to arrange that an instance be attached to the task.  Does something else need to be added to .cirrus.yml?  Does something need to be changed in some other configuration?

(I note that I couldn't find anything corresponding to a *reference manual* for Cirrus CI YML, describing everything that can be done; there's only a user's guide that doesn't have the form of a reference manual.)
