### ISSUE TITLE
OpenBSD, agent is not responding when compute_engine_instance is used

### ISSUE THREAD

**Issue by nbyavuz** [cirruslabs/cirrus-ci-docs#1045]
Hi,

OpenBSD gives `Agent is not responding!` error when I use `compute_engine_instance`, but if I use `gce_instance` instead of `compute_engine_instance` it works correctly.

[Example run](https://cirrus-ci.com/build/6299173023645696) and [config](https://github.com/nbyavuz/cirrus-playground/blob/f143597203a3e81d5c465ad81d622e0017000cf9/.cirrus.yml).

Could the error be on the Cirrus side?

Thanks!

**Comment by fkorotkov** [comment]
@nbyavuz could you please try a TAU instance for your `gce_instance`? I wonder if your image doesn't work on Amd. 

```yaml
gce_instance:
  image_project: pg-ci-images-dev
  image_family: pg-ci-openbsd-7-1-postgres
  platform: openbsd
  type: t2d-standard-4
  disk: 25
```

To force a `compute_engine_instance` to use Intel you can use `nested_virtualization: true`.
