### ISSUE TITLE
RFE: AWS EC2 instance name-tags

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#1051]
# Description

When creating AWS EC2 instances, Cirrus-CI should set the `Name` tag using a format similar to GCE's 'cirrus-task-<task number>`.

# Context

In GCE, VMs are conveniently named with `cirrus-task-<blah>` which is very helpful for overall observability.  This would be a handy feature to have in AWS where instances are (otherwise) only identified by their utterly unreadable, generated IDs.  Especially when VMs from other contexts are mixed in (for example, developer debug VMs).  They're also handy on the off-chance something really horrible happens in CI and direct-access to the VM is required for debugging.

# Anything Else

This isn't a high-priority for my team at the moment, but would be a "nice to have" feature.

**Comment by fkorotkov** [comment]
The problem is that Cirrus will need see `ec2:CreateTags` permission (see [7551fd0](https://github.com/cirruslabs/cirrus-ci-docs/commit/7551fd045aee52bc4b64572b15f3d151cfd65a9a)). Otherwise it will break instance scheduling.

I've updated the documentation and will reach out to people using Cirrus CI on AWS so they can update permissions. In the meantime if you enabled the permission you can try taggin via `experimental` flag:

```yaml
ec2_task:
  experimental: true
  ec2_instance:
    image: ubuntu/images/*ubuntu-jammy-22.04-arm64-server-*
    architecture: arm64
    region: us-east-2
    type: a1.metal
  script: printenv
```
