### ISSUE TITLE
Grab latest deb, rpm, or other types from master and other possible branches?

### ISSUE THREAD

**Issue by kaosine** [cirruslabs/cirrus-ci-docs#1076]
# Description

Basically I help out with pulsar-edit/pulsar especially through our documentation team, and we'd like to provide links that will be plugged in on our readme's and website. The current documentation isn't clear if this is possible, unless it involves not putting the version number in the name or wildcarding.

# Context

With how our builds are generated, you see something like this like pulsar-edit-<insert version number which includes a date since we've not figured out resetting ours and not be weird about stuff>.deb

We need to be able to grab and properly release these as links on the website, and it'd be nice to do the same elsewhere. I've gotten as far as the alias part, but binary/binaries/binary-name.deb is where i get stuck to make sure we can grab these...

**Comment by fkorotkov** [comment]
Have you looked into [`artifacts` instruction](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction)? If you have something like:

```yaml
task:
  name: Build Deb
  alias: deb_build
  # some instructions to build things
  deb_artifacts:
     path: binary/binaries/binary-name.deb
```

Then you can refer to it the file as https://api.cirrus-ci.com/v1/artifact/github/pulsar-edit/pulsar /deb_build/deb/binary/binaries/binary-name.deb. You can also specify `branch` query parameter to specify a branch to look up from.
