### ISSUE TITLE
Cache hit macOS permissions

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#1087]
## Expected Behavior

Restored from CI cache executable has correct permissions.

After cache reset: https://cirrus-ci.com/build/5438662258196480

## Real Behavior

```
codecov/uploader
/var/folders/xx/vl5f934s6k927z1vyyl9cxth0000gn/T/scripts5fb90badb37c5821b6d95526a41a9504.sh: line 5: codecov/uploader: cannot execute binary file
Exit status: 126
```

https://cirrus-ci.com/task/6095845136269312?logs=codecov#L0

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: `macOS`
  - Task name: `Test on darwin`
  - Script/cache name (if applies): `codecov_cache`

# Configuration

```yaml
env:
  CODECOV_OS: macos

codecov_uploader_cache:
  folder: codecov
  fingerprint_script:
    - curl -Os https://uploader.codecov.io/latest/${CODECOV_OS}/codecov.SHA256SUM
  populate_script:
    - mkdir -p codecov
    - curl -s https://uploader.codecov.io/latest/${CODECOV_OS}/codecov -o codecov/uploader
    - chmod +x codecov/uploader

codecov_script: codecov/uploader
```

**Comment by AlexWayfer** [comment]
Probably it's not only about macOS: https://cirrus-ci.com/task/4925892018307072

**Comment by edigaryev** [comment]
Unfortunately, I wasn't able to reproduce your example: https://cirrus-ci.com/task/5442098164924416.

Here's a full `.cirrus.yml`:

```yaml
env:
  CODECOV_OS: macos

task:
  macos_instance:
    image: monterey-base

  codecov_uploader_cache:
    folder: codecov
    fingerprint_script:
      - curl -Os https://uploader.codecov.io/latest/${CODECOV_OS}/codecov.SHA256SUM
    populate_script:
      - mkdir -p codecov
      - curl -s https://uploader.codecov.io/latest/${CODECOV_OS}/codecov -o codecov/uploader
      - chmod +x codecov/uploader

  codecov_script: codecov/uploader
```

Or I am missing something here?
