### ISSUE TITLE
docker_builder as a field for a task does not work

### ISSUE THREAD

**Issue by adelton** [cirruslabs/cirrus-ci-docs#1102]
## Expected Behavior

What should have happened is: I started with a working configuration
```
test_task:
  arm_container:
    image: busybox:latest
  test_script: uname -a
```
which passed at https://cirrus-ci.com/task/6172341726609408.

I followed advice from https://cirrus-ci.org/guide/writing-tasks/#execution-environment which says
> In order to specify where to execute a particular task you can choose from a variety of options by defining one of the following fields for a task:
> arm_container ...
> docker_builder ...

So I just changed `arm_container` to `docker_builder` to get
```
test_task:
  docker_builder:
    env:
      CIRRUS_ARCH: arm64
  test_script: uname -a
```
making that `docker_builder` a field of the task per documentation.

## Real Behavior

What ended up happening was that this lead to an errored job https://cirrus-ci.com/build/5972226382495744 which said

> task has no instance or container attached, consult the documentation to find all possible execution environment types

So it does not seem true that to get `docker_builder` execution environment, you should specify it as a field of the task, the same way you would for `arm_container`.

Instead, I had to specify the `docker_builder` *instead* of that task declaration:
```
docker_builder:
  env:
    CIRRUS_ARCH: arm64
  test_script: uname -a
```
This lead to a passing job https://cirrus-ci.com/build/4711344511909888. It seems like `docker_builder` is some syntactic sugar rather than a proper task field.

Either the documentation should be changed to explain what the exact deal with `docker_builder` is, to match the behaviour; or the behaviour of Cirrus CI should be changed to actually accept `docker_builder` as a task field, per documentation.

# Related Info

This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/writing-tasks/
  - But maybe the documentation is actually correct and the behaviour is broken?
- [ ] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):
