### ISSUE TITLE
The example for docker_config_file is not correct

### ISSUE THREAD

**Issue by julien-carsique-sonarsource** [cirruslabs/cirrus-ci-docs#1111]
## Expected Behavior

The following snippet from the documentation should allow customizing the docker configuration.
```
task:
  environment:
    DOCKER_CONFIG: ENCRYPTED[qwerty]
  docker_config_file:
    path: /root/.docker/config
    variable_name: DOCKER_CONFIG
```

## Real Behavior

DOCKER_CONFIG is a reserved keyword by Docker. Using it breaks the Docker configuration resolution.
The correct file path is `/root/.docker/config.json`.

# Related Info

This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/writing-tasks/#file-instruction
- [ ] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies):
