### ISSUE TITLE
FreeBSD runners have low disk space

### ISSUE THREAD

**Issue by hasufell** [cirruslabs/cirrus-ci-docs#1123]
I'm currently using Cirrus CI for ghcup, which is the main Haskell installer and HLS, which is the Haskell LSP Server. I build them on FreeBSD on Cirrus CI.

I frequently have issues with running out of space, although I already try hard to remove intermediate artifacts.

Latest example: https://cirrus-ci.com/task/6355502150451200

**Comment by fkorotkov** [comment]
You can change your disk size:

```yaml
freebsd_instance:
  image_family: freebsd-13-1
  disk: 100
```

This way you won't be restricted by the default disk size that the images have. 👌

**Comment by hasufell** [comment]
Can you explain what the value does? GB? Percent of something? There seems to be no documentation for this.

I set it to 100 and 150 and still get out of disk space errors: 

https://cirrus-ci.com/task/4730447451127808?logs=main#L6006

```
ghcup: /tmp/cirrus-ci-build/.ghcup/logs/ghcup.log: withFile: resource exhausted (No space left on device)
```

https://github.com/haskell/haskell-language-server/blob/9f8ce8f1e927d8b286fbf8886dfd040f9ce251da/.cirrus.yml#L3

**Comment by fkorotkov** [comment]
My bad. Indeed `freebsd_instance` just uses the default disk size and it's not possible to customize it.

Thankfully `freebsd_instance` is a [`compute_instance`](https://cirrus-ci.org/guide/custom-vms/) under the hood and you can workaround it with a little more lines:

```yaml
compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-13-1
  platform: freebsd
  disk_size: 100 # Gb
```

**Comment by hasufell** [comment]
That did not work either: https://cirrus-ci.com/build/6635511201136640

100GB should be enough for this job to succeed.

**Comment by hasufell** [comment]
Since this is not fixed, please re-open the ticket.

**Comment by fkorotkov** [comment]
My bad. The option is `disk` and not `disk_size`. The following config [works](https://cirrus-ci.com/task/5319403164663808?logs=disk#L2):

```yaml
compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-13-1
  platform: freebsd
  disk: 100 # Gb

freebsd13_task:
  disk_script: df -h
```
