### ISSUE TITLE
Support coveralls

### ISSUE THREAD

**Issue by xster** [cirruslabs/cirrus-ci-docs#118]
Support https://docs.coveralls.io/supported-ci-services coverage tracking service.

**Comment by fkorotkov** [comment]
I think it should be possible to add it right now via specifying environment variables that Coverall expects:

```
env:
  CI_NAME: "CirrusCI"
  CI_BUILD_NUMBER: $CIRRUS_TASK_ID
  CI_BUILD_URL: "https://cirrus-ci.com/task/$CIRRUS_TASK_ID"
  CI_BRANCH: $CIRRUS_BRANCH
  CI_PULL_REQUEST: $CIRRUS_PR
```

I'll try to ping Coverall to add the support. In the meantime you can try the environment variables above. Note that for private repos you'll need to specify `COVERALLS_REPO_TOKEN`

**Comment by fkorotkov** [comment]
@xster which coverall integration are you using? Ruby?

**Comment by xster** [comment]
it seems like we're using https://github.com/okkez/coveralls-lcov

**Comment by fkorotkov** [comment]
Oh. There is only travis ci support baked in. In any case I don't think there is something on Cirrus CI that should be done. It's just a matter of supporting it in the downstream librarie/runners.

For example, with the runner from documentation (https://github.com/lemurheavy/coveralls-ruby) the environment variables above should make coverall work.

**Comment by fkorotkov** [comment]
Will close the issue since there is nothing to to added on Cirrus CI side. Coverall reporters should respect `CIRRUS_*` variables. Let's create issues in the reporters repositories and work on support there.

**Comment by dnfield** [comment]
I found this via google.

I got coveralls working using cirrus on a Flutter image like so:

```yaml
container:
  image: cirrusci/flutter:latest

env:
  CI_NAME: "CirrusCI"
  CI_BUILD_NUMBER: $CIRRUS_TASK_ID
  CI_BUILD_URL: "https://cirrus-ci.com/task/$CIRRUS_TASK_ID"
  CI_BRANCH: $CIRRUS_BRANCH
  CI_PULL_REQUEST: $CIRRUS_PR
  COVERALLS_REPO_TOKEN: ENCRYPTED[61ba3fee193a9ed6116e0f61bbe26fe8c0452287e5dfd86c728e2f1f24327818d6c74c956d7b9cbf3bd6236489af0fd1]

test_task:
  pub_cache:
    folder: ~/.pub-cache
  analyze_script: flutter analyze .
  test_script: flutter test --coverage
  coveralls_script: |
    dart pub global activate coveralls
    dart pub global run coveralls coverage/lcov.info
```

Where COVERALLS_REPO_TOKEN is the token from coveralls.io fed through the encyrpted settings in the Cirrus dashboard.
