### ISSUE TITLE
`dockerfile` support for `gce_container`

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#1186]
# Description

It appears like currently this does not work:

```yaml
gce_container:
  image_project: my-project
  image_name: my-custom-ubuntu-with-docker-and-KVM
  dockerfile: ./Dockerfile
 ```

Currently this will create a VM and a job that just hangs forever/never fully starts.
Would it be possible to add support for this to `gce_container`?

Best, Christian
