### ISSUE TITLE
Specifying tasks types via environment variable / overriding task types

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#1215]
Hi,

For an open source process it makes a lot of sense to allow everyone to use cirrus-ci in their forks using the "free" credits, but to use custom compute or persistent runners for the, commonly much higher, usage of the project itself. The switch would need to happen based on what's present in repository level environment variables. Right now that's somewhat painful to implement in `.cirrus.yml` however.

Part of the issue are some small differences in the way tasks are specified. E.g. for `custom_engine_instance:` image families are specified via `image: family/docker-kvm` whereas for `gce_instance:` they are specified as ` image_family: ubuntu-2204-lts-arm64`.

My current best guess for how to implement this is something roughly like:
```yml
linux_instance: &linux_instance
  matrix:
    - only_if: $BUILD_METHOD == 'ours'
      gce_instance:
        image_family: $image_family

    - only_if: $BUILD_METHOD == 'cirrus'
      compute_engine_instance:
        image: family/$image_family

macos_instance: &macos_instance
  matrix:
    - only_if: $BUILD_METHOD == 'ours'
      persistent_worker:
        isolation:
          tart:
            image: $image

    - only_if: $BUILD_METHOD == 'cirrus'
      macos_instance:
        image: $image

task:
  name: some linux task
  env:
    image_family: some-image
  <<: *linux_instance

task:
  name: some macos task
  env:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  <<: *macos_instance
```

Which does end up somewhat painful...

Thanks,

Andres
