### ISSUE TITLE
Incomplete and uneven CPU and Memory usage graphs

### ISSUE THREAD

**Issue by igsilya** [cirruslabs/cirrus-ci-docs#1217]
## Expected Behavior

Resource usage graphs should cover the whole time job was running (at least, approximately) and data points should be evenly distributed.

## Real Behavior

The CPU usage graph shows one sample per minute.  On it's own it's not frequent enough, but that's not the main issue.  The main problem is that it doesn't show the last couple of minutes of the run.  For example, for some of our 5-ish minute runs we have data points at 0, 1 and 2 minutes.  While minutes 4 and 5 are the most CPU intensive in our jobs and are not sampled at all.  Having a bit more frequent samples would be nice as well.

The memory usage graph contains many samples that cover the full run, but it is just weird.  The graph is uneven and stretched, because the data is sampled each second within the first minute, and then it is sampled each 10 seconds.  The graph is not adjusted for the sampling rate change.

# Related Info

The issue doesn't depend on the OS or a project.  Mostly affects shorter jobs, since the effects of not having data for a last 2-3 minutes of a 5-minute run or overstretching of a graph are much more visible.

This is a (tick one of the following):

- [x ] Task issue
  - OS: FreeBSD, Linux
  - Example: https://cirrus-ci.com/task/5695223901192192

**Comment by edigaryev** [comment]
Hello Ilya, thanks for reporting this!

This should be fixed now, including [the task you've mentioned](https://cirrus-ci.com/task/5695223901192192).

**Comment by edigaryev** [comment]
Hello Ilya!

I've checked this again and I doubt that the CPU chart is stretched. The sampling rate indeed changes, but the values produced have the correct timestamp attached to them. You can check this via the [GraphQL explorer](https://cirrus-ci.com/explorer) for your task using the following query:

```graphql
query {
  task(id: 5695223901192192) {
    executionInfo {
      cpuChart {
        points {
          secondsFromStart
          value
        }
      }
    }
  }
}
```

I've made the following synthetic test that should use ~1.5 CPU for the whole duration:

```yaml
task:
  freebsd_instance:
    matrix:
      image_family: freebsd-12-4-snap
      image_family: freebsd-13-2-snap
    cpu: 4
    memory: 4G

  install_stress_ng_script:
    - pkg update -f
    - pkg install -y stress-ng

  run_stress_ng_script:
    - stress-ng -t 600 --cpu 2 --cpu-load 75
```

And [it resulted](https://cirrus-ci.com/task/5074510664171520) in an even CPU graph:

<img width="852" alt="Screenshot 2023-08-25 at 11 39 15" src="https://github.com/cirruslabs/cirrus-ci-docs/assets/85709/8fe9072c-3f4c-4d6e-a672-37fdc44ae26d">

Did I miss something?
