### ISSUE TITLE
Support inline content in file instruction

### ISSUE THREAD

**Issue by nbraud** [cirruslabs/cirrus-ci-docs#1247]
# Description

In [file instructions][file], accept a `content` attribute which contains the file's desired contents, as a string:
```yaml
file:
  path: /etc/foo
  contents: foo
```

That attribute should be mutually-exclusive with `variable_name`.

# Context

Currently, the only (documented) way to use a [file instruction][file] is rather verbose for simple cases:
```yaml
env:
  FILE_CONTENTS: foo
file:
  path: /etc/foo
  variable_name: FILE_CONTENTS
```

[file]: https://cirrus-ci.org/guide/writing-tasks/#file-instruction

# Anything else

`file.contents` could support shell-style variable expansion, but that isn't necessary for simpler use-cases.
