### ISSUE TITLE
Build cache is always missing on macOS (but present in linux /windows containers and FreeBSD) - possible regression?

### ISSUE THREAD

**Issue by abravalheri** [cirruslabs/cirrus-ci-docs#1291]
A couple of years ago, I implemented the methodology described in https://github.com/cirruslabs/cirrus-ci-docs/issues/776#issuecomment-771644379 that uses the `cache` instruction[^1] to transfer files between different tasks and that worked nicely for a few years, but now the cache seems to always be missing on macos.

The `.cirrus.yaml` file can be found in
 https://github.com/pyscaffold/pyscaffold/blob/3470d35aee120c07311d8c50b4844f80fa8fde94/.cirrus.yml, and in summary it works like the following:

- A `build` task builds the project and uses the `cache` instruction to store the "installable" files[^2]:

```yaml
build_task:
  name: build and check (Linux - 3.11)
  alias: build
  container: {image: "python:3.11-bullseye"}
  clone_script: *clone
  dist_cache:  # build once and upload to be used by other tasks
    folder: dist
    fingerprint_key: $CIRRUS_BUILD_ID
    reupload_on_changes: true
  <<: *task-template
  install_script: pip install tox
  build_script: tox -e clean,lint,typecheck,build
```

[^2]: In the past I used to have `fingerprint_script: echo $CIRRUS_BUILD_ID`, but in order to debug this issue I have just changed it to `fingerprint_key: $CIRRUS_BUILD_ID`.

- Later the "test" tasks in different platforms download these installable files, install and test them:

```yaml
.test_template: &test-template
  # Requires pip, tox, and pipx to be installed via OS/pip
  alias: test
  depends_on: [build]
  <<: *task-template
  dist_cache: {folder: dist, fingerprint_key: $CIRRUS_BUILD_ID}  # download
  test_script: >
    tox --installpkg dist/*.whl -e all --
    -n 5 --randomly-seed=42 -rfEx --durations 10 --color yes

linux_task:
  matrix:
    - name: test (Linux - 3.7)
      container: {image: "python:3.7-bookworm"}
    - name: test (Linux - 3.10)
      container: {image: "python:3.10-bookworm"}
      skip: $BRANCH !=~ "^(main|master)$"
    - name: test (Linux - 3.12)
      container: {image: "python:3.12-bookworm"}
    - name: test (Linux - 3.13)
      container: {image: "python:3.13-rc-bookworm"}
      allow_failures: true  # Experimental
  install_script:
    - python -m pip install --upgrade pip tox pipx
  <<: *test-template
  alias: base-test

mamba_task:
  name: test (Linux - mambaforge)
  container: {image: "condaforge/mambaforge"}
  install_script:  # Overwrite template
    - mamba install -y pip pipx tox curl
  <<: *test-template
  depends_on: [base-test]

macos_task:
  name: test (macOS - brew)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    PATH: "/opt/homebrew/opt/python/libexec/bin:${PATH}"
  brew_cache: {folder: "$HOME/Library/Caches/Homebrew"}
  install_script: brew install python tox pipx
  <<: *test-template
  depends_on: [build, base-test]

freebsd_task:
  name: test (freebsd - 3.11)
  freebsd_instance: {image_family: freebsd-14-0}
  install_script:
    - pkg remove -y python lang/python
    - pkg install -y git vim python311 py311-pip py311-gdbm py311-sqlite3 py311-tox py311-tomli py311-pipx
    - ln -s /usr/local/bin/python3.11 /usr/local/bin/python
  <<: *test-template
  depends_on: [build, base-test]

windows_task:
  name: test (Windows - 3.12.5)
  windows_container:
    image: "cirrusci/windowsservercore:2019"
    os_version: 2019
  env:
    CIRRUS_SHELL: bash
    PATH: /c/Python312:/c/Python312/Scripts:/c/tools:${PATH}
  install_script:
    # Activate long file paths to avoid some errors
    - ps: New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
    - choco install -y --no-progress python3 --version=3.12.5 --params "/NoLockdown"
    - choco install -y --no-progress vim
    - pip install --upgrade certifi
    - python -m pip install -U pip tox pipx
  <<: *test-template
  depends_on: [build, base-test]
```

[^1]: Note that I intentionally did not try to use the `artifacts` instruction because that one is more cumbersome and difficult to get write. Moreover it also implies that I would need to find a way to implement the download/"unzip-ing" of the artifacts in a cross platform (which probably would mean that I have to implement conditionals for platforms like windows that do not natively have the `unzip` command line tool).

## Expected Behavior

I expect the `cache` instruction to work as it works in the other platforms and download the cached files on macOS (this used to be the case).

## Real Behavior

Currently the cache is always missing on macos: `Cache miss for 6174398904795136! No script to populate with.` (https://cirrus-ci.com/task/5300527074902016?logs=dist).

However, the cache hits fine on all the other platforms:
- linux - `Downloaded 5Mb in 0.231626s. Cache hit for 6174398904795136!`: https://cirrus-ci.com/task/4737577121480704?logs=dist#L2 
- windows - `Downloaded 5Mb in 0.168433s. Cache hit for 6174398904795136!`: https://cirrus-ci.com/task/5019052098191360?logs=dist#L2
- freebsd - `Downloaded 5Mb in 0.161831s. Cache hit for 6174398904795136!`: https://cirrus-ci.com/task/6426426981744640?logs=dist#L2

Also note that in order to investigate this better I added the following to all the test tasks:

```yaml
  check_cache_exists_script:
    - curl -I -k http://$CIRRUS_HTTP_CACHE_HOST/dist-$CIRRUS_BUILD_ID
    - curl -I -k http://$CIRRUS_HTTP_CACHE_HOST/dist-\$CIRRUS_BUILD_ID
```

This was inspired by the following passage on the [docs](https://cirrus-ci.org/guide/writing-tasks/#http-cache):

> Cirrus CI agent starts a local caching server and exposes it via CIRRUS_HTTP_CACHE_HOST environments variable. Caching server supports GET, POST, HEAD and DELETE requests to upload, download, check presence and delete artifacts.
> For example running the following command:
>
> `curl -s -X POST --data-binary @myfolder.tar.gz http://$CIRRUS_HTTP_CACHE_HOST/name-key`
>
> ...has the same effect as the following [caching instruction](https://cirrus-ci.org/guide/writing- tasks/#cache-instruction):
>
> ```yaml
> name_cache:
>   folder: myfolder
>   fingerprint_key: key
> ```

So I was expecting that the cache previously uploaded with:

```yaml
  dist_cache:  # build once and upload to be used by other tasks
    folder: dist
    fingerprint_key: $CIRRUS_BUILD_ID
    reupload_on_changes: true
```

would be available for inspection in the follow-up tasks in the URL `http://$CIRRUS_HTTP_CACHE_HOST/dist-$CIRRUS_BUILD_ID`.

However, that does not seem to be the case. The output of that script always shows a 404 error in all platforms, even when the cache is hit ([linux](https://cirrus-ci.com/task/4737577121480704?logs=check_cache_exists#L6), [freebsd](https://cirrus-ci.com/task/6426426981744640?logs=check_cache_exists#L6), [windows](https://cirrus-ci.com/task/5019052098191360?logs=check_cache_exists#L6), [macos](https://cirrus-ci.com/task/5300527074902016?logs=check_cache_exists#L6)). That seems to contradict the docs, no?

# Related Info

This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/writing-tasks/#http-cache
- [x] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name:
  - Script/cache name (if applies): `dist_cache`

**Comment by fkorotkov** [comment]
We recently made a change where macOS caches are stored in another storage then Linux/Windows/FreeBSD so sharing caches between OS like that won't work.

For such smoke testing of binaries please consider using `artifacts` instruction and using Cirrus REST API to download them in smoke test tasks. This way downloading will be redirected to the correct cloud.

**Comment by abravalheri** [comment]
Thank you for the clarification, @fkorotkov.

I understand the change regarding macOS. However the second problem described above with the documentation of the HTTP cache, still looks problematic no?

The following is [documented](https://cirrus-ci.org/guide/writing-tasks/#http-cache):

> Cirrus CI agent starts a local caching server and exposes it via CIRRUS_HTTP_CACHE_HOST environments variable. Caching server supports GET, POST, HEAD and DELETE requests to upload, download, check presence and delete artifacts.
> For example running the following command:
>
> `curl -s -X POST --data-binary @myfolder.tar.gz http://$CIRRUS_HTTP_CACHE_HOST/name-key`
>
> ...has the same effect as the following [caching instruction](https://cirrus-ci.org/guide/writing- tasks/#cache-instruction):
>
> ```yaml
> name_cache:
>   folder: myfolder
>   fingerprint_key: key
> ```

So if I uploaded the cache previously uploaded with:

```yaml
  dist_cache:  # build once and upload to be used by other tasks
    folder: dist
    fingerprint_key: $CIRRUS_BUILD_ID
    reupload_on_changes: true
```

I should be able to inspect the cache in the follow-up tasks (except macOS as you pointed out in your comment) using the URL `http://$CIRRUS_HTTP_CACHE_HOST/dist-$CIRRUS_BUILD_ID`.

However, that does not seem to be the case.

Even with the cache downloading normally, the output of that script always shows a 404 error in all platforms, even when the cache is hit ([linux](https://cirrus-ci.com/task/4737577121480704?logs=check_cache_exists#L6), [freebsd](https://cirrus-ci.com/task/6426426981744640?logs=check_cache_exists#L6), [windows](https://cirrus-ci.com/task/5019052098191360?logs=check_cache_exists#L6).

That seems to be contradictory with the docs, no?
