### ISSUE TITLE
socket.getfqdn("127.0.0.1") takes 35 seconds on MacOS Sequoia

### ISSUE THREAD

**Issue by awelzel** [cirruslabs/cirrus-ci-docs#1302]
## Expected Behavior

`socket.getfqdn("127.0.0.1")` returns "localhost" quickly on MacOS Sequoia.

## Real Behavior

The call takes 35 seconds to complete in our testing environment:
```
admin@admins-Virtual-Machine zeek % python3 -c 'import socket, time; s=time.time(); print(socket.getfqdn("127.0.0.1")); e=time.time(); print(e - s)'
localhost
35.00473499298096
```
We use Python's `http.server` to create a testing http server listening on `127.0.0.1`. The Python code internally does `socket.getfqdn(listen_addr)` to determine the server name. Due to this taking 35 seconds, the test timeout is reached much before.

# Related Info

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: (Docker, macOS, Windows, FreeBSD)
  - Task name: macos_sequoia (https://cirrus-ci.com/task/4963337030598656)
  - Script/cache name (if applies):

PR for upgrade: https://github.com/zeek/zeek/pull/4284#issuecomment-2729118359

**Comment by edigaryev** [comment]
Hello Arne,

I've tried to reproduce this with the following CI configuration:

```yaml
task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sequoia

  check_script:
    - python3 -c 'import socket, time; s=time.time(); print(socket.getfqdn("127.0.0.1")); e=time.time(); print(e - s)'
```

And got [the following result](https://cirrus-ci.com/task/4879816828125184):

```
[12:39:04.594] python3 -c 'import socket, time; s=time.time(); print(socket.getfqdn("127.0.0.1")); e=time.time(); print(e - s)'
[12:39:06.692] 1.0.0.127.in-addr.arpa
[12:39:06.692] 0.029513120651245117
```

Perhaps there's some other variable at play besides just resolving the `127.0.0.1`?
