### ISSUE TITLE
Support creation of GCE VMs and GKE containers in all zones

### ISSUE THREAD

**Issue by Godin** [cirruslabs/cirrus-ci-docs#160]
Looks like resolution of #40 was partial - following usage of `europe-west1-b` zone

```
gcp_credentials: ENCRYPTED[...]

task:
  gce_instance:
    image_project: ubuntu-os-cloud
    image_name: ubuntu-1404-trusty-v20190209
    type: n1-standard-1
    disk: 10
    zone: europe-west1-b
  script: echo OK
```

results in

```
FAILED_PRECONDITION: java.lang.IllegalArgumentException: Not supported at the moment zone europe-west1-b!
```

while

```diff
-    zone: europe-west1-b
+    zone: europe-west3-a
```

works. I'm wondering why there is any difference between these two and any others? Is it possible to find somewhere a list of zones supported by Cirrus CI? Or maybe you can just add support for all zones? Thanks.
