### ISSUE TITLE
Support Private Docker Registries

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#163]
At the moment the only way to use private registries is to use [Google Kubernetes Engine integration](https://cirrus-ci.org/guide/supported-computing-services/#kubernetes-engine) to leverage GCR or [automated authentication through a service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account).

It will be great to be able securely use such private images for OSS projects or projects that use [compute credits](https://cirrus-ci.org/pricing/#compute-credits).

Proposed syntax:

```yaml
container:
  image: ...
  registry_config: ENCRYPTED[...]
```

or
 
```yaml
registry_config: ENCRYPTED[...]
container:
  image: node:latest
  additinal_containers:
    - name: db
      image: somePrivateImageOfAnEnterpriseDB:latest
```

Where `registry_config` uses [encrypted variables](https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables) to securely provide `.dockerconfigjson`.

Related issues with Oracle DBs: https://github.com/oracle/docker-images/issues/1156
