### ISSUE TITLE
Support forcing cache repopulation

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#173]
I have a cache of dependencies for my tests, but when my dependency updating bot automatically bumps dependencies, I don’t think they are being included in the cache for a while. Would love to see something like:

```yaml
my_cache:
  folder: node_modules
  force_repopulate: $CIRRUS_BRANCH == “update_deps”
  populate_script: yarn
```
