### ISSUE TITLE
Failed to start task

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#175]
My build just failed with the following error:  

`Exception on the agent! Failed to initialize command clone log upload: open C:\Users\ContainerAdministrator\AppData\Local\Temp\clone644086951: The system cannot find the path specified.`  

Just thought I should report this

**Comment by fkorotkov** [comment]
@RDIL could you please provide a link to the task?

**Comment by RDIL** [comment]
@fkorotkov sure, 
https://cirrus-ci.com/build/5167722330587136
(The task called Win)

**Comment by fkorotkov** [comment]
Have you tried to re-run? Seems like network relater issue. 🤔

**Comment by RDIL** [comment]
Yes, that was the second commit in a row with that error.

**Comment by fkorotkov** [comment]
Did you delete the branch? Can't find it in https://github.com/area4lib/area4 to see the config of `Win` task...

**Comment by RDIL** [comment]
Oh, looks like a friend of mine did.  I know the config was:
```yaml
task:
  name: Win
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    CIRRUS_SHELL: powershell
  use_compute_credits: true
  auto_cancellation: true
  prep_script: ./cirrus-bootstrap.ps1
  script: ./cirrus-windows2019task.ps1
```
