### ISSUE TITLE
Support Templates

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#176]
Coming soon: template use like in Azure Pipelines.  
For example:

`.cirrus.yml`:
```yaml
test_task:
  template: /tools/build.yml
```
`/tools/build.yml`:
```yaml
container:
  image: whateverimage:version
script: echo hi
```

Basically you have instructions in another file and Cirrus reads the file and applies it automatically.

**Comment by fkorotkov** [comment]
I've been thinking about this exact feature to extend of supporting templates outside of the repository. Imagine having the following `.cirrus.yml` file for your Golang application:

```yaml
template: cirrus-ci-templates/golang
```

Or if you want to get only a specific task from the template:

```yaml
template: cirrus-ci-templates/golang@1.0.0/build
```

Also this templates will be able to use [Mustache](https://mustache.github.io/) templates to allow generation of tasks like this:

```yaml
template: 
  location: cirrus-ci-templates/golang@1.0.0/test
  go_versions:
    - 1.12
    - 1.11
    - 1.10
```

And the template will look like this:

```yaml
test_task:
  container:
    matrix:
      {{#go_versions}}
      image: golang:{{#.}}
      {{/go_versions}}
  
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME
  get_script: go get -t -v ./...
  test_script: go test -v ./...
```
