### ISSUE TITLE
Dockerfile as content and not a file path

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#182]
It will be nice to support inlining of Dockerfiles like this:

```yaml
task:
  env:
    matrix:
        GO_VERSION: 1.12
        GO_VERSION: 1.11
  container:
    dockerfile: >
      FROM golang:$GO_VERSION
      RUN apk add --no-cache foo
  script: ...
```
