### ISSUE TITLE
Environment variables set in script do not persist to next

### ISSUE THREAD

**Issue by kne42** [cirruslabs/cirrus-ci-docs#19]
Part of my installation process requires me to set an environment variable from within a script. However, these variables do not seem to persist to the next script no matter how or where I export them.

On Unix I have tried:
```
export FOO=42
echo 'export FOO=42' > ~/.profile
echo 'export FOO=42' > ~/.bash_profile
echo 'export FOO=42' > ~/.bashrc
```
But upon starting up a new script, bash doesn't recognize `$FOO`.

ie the following specification does not behave as I would expect (`echo`ing `42`):
```yaml
set_script:
  - export FOO=42
  - echo 'export FOO=42' > ~/.profile
  - echo 'export FOO=42' > ~/.bash_profile
  - echo 'export FOO=42' > ~/.bashrc
  - echo $FOO
> 42
test_script:
  - cat ~/.profile
> export FOO=42
  - cat ~/.bash_profile
> export FOO=42
  - cat ~/.bashrc
> export FOO=42
  - echo $FOO
> 
```

Similarly on Windows, `SET`, `SETX`, nor `[Environment]::SetEnvironmentVariable` persist the environment variable past the script they were called from.

In particular, I am actually modifying the `PATH` variable, which unfortunately causes problems for when it is parsed under `env` since I am referring to existing variables with the proper batch and bash syntax. So yeah, it seems like I have set this by script but that isn't exactly going so well... 😅

I'm completely baffled by this and any help would be greatly appreciated.

**Comment by fkorotkov** [comment]
@kne42 have you tried to `source ~/.bash_profile` after changing it? I think you should explicitly call it.

**Comment by kne42** [comment]
@fkorotkov It gives me this error when I try to do that:
```
source ~/.bash_profile
/tmp/scripts1e00167939cb6694d2c422acd208a007.sh: 7: /tmp/scripts1e00167939cb6694d2c422acd208a007.sh: source: not found
```

Which means I have to use `.` so I guess the bash that you guys are using is weird. Anyways, I didn't realize that you were just making temp script files and calling them with `sh temp.sh`, since in most other CIs, they `source` the script instead or insert it directly into the command line.

To get the functionality that I desire, it looks like I'll have to make a dockerfile...

**Comment by fkorotkov** [comment]
@kne42 which Docker image are you using right now?

Other CI generate a single script where Cirrus CI generates a script for each `script` instruction. Workaround could be to just combine `set_script` and `test_script`. But please let me know which image are you using right now.

You can also try to use `bash` instead of `sh` by specifying `CIRRUS_SHELL` environment variable:

```yaml
env:
   CIRRUS_SHELL: bash

task:
  ...
```

**Comment by kne42** [comment]
It also looks like making a custom Dockerfile isn't doing anything either: https://cirrus-ci.com/task/5397385802940416

**Comment by fkorotkov** [comment]
Interesting... If you don't want to use `CIRRUS_SHELL` and `source` you can simply modify `env` which will look something like this:

```yaml
task:
  matrix:
    - container:
        image: gcc:latest
      conda_script:
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > install.sh
        - bash ./install.sh -b -p $HOME/conda
      env:
        PATH: $HOME/conda/bin:$PATH

    - windows_container:
        image: cirrusci/windowsservercore:2016
      conda_script:
        - powershell -Command "curl https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile install.exe"
        - start /wait "" install.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%cd%\anaconda
        - SETX PATH %PATH%;%cd%\anaconda\Scripts;%cd%\anaconda
        - pip install setuptools-scm

    - osx_instance:
        image: high-sierra-xcode-9.4.1
      conda_script:
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > install.sh
        - bash ./install.sh -b -p $HOME/conda
      env:
        PATH: $HOME/conda/bin:$PATH

  install_script:
    - python -m pip install --retries 3 upgrade pip
    - pip install --retries 3 -r requirements.txt

  pipcheck_script:
    - pip list

  test_script:
    - pytest -v
```

**Comment by kne42** [comment]
@fkorotkov This worked, thank you!

This also works on Windows, but do note that environment variables follow the syntax `$VAR` instead of `%VAR%` when set under `env`.

I ended up using:
```yaml
env:
  PATH: $PATH;C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\anaconda\Scripts;C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\anaconda
```
I would have liked to use `$CIRRUS_WORKING_DIR` but for some reason in Windows it looks like this variable is set after the other assignments (i.e. `env: FOO:$CIRRUS_WORKING_DIR` is not behaving as expected).

This is the fully updated `.cirrus.yml` for reference:
```yaml
task:
  matrix:
    - name: linux
      container:
        image: gcc:latest
      conda_script:
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > install.sh
        - bash ./install.sh -b -p $HOME/conda
      env:
        PATH: "$HOME/conda/bin:$PATH"

    - name: windows
      windows_container:
        image: cirrusci/windowsservercore:2016
      conda_script:
        - powershell -Command "curl https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe -OutFile install.exe"
        - start /wait "" install.exe /InstallationType=AllUsers /AddToPath=1 /RegisterPython=1 /S /D=%cd%\anaconda
        - pip install setuptools-scm
      env:
        PATH: $PATH;C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\anaconda\Scripts;C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\anaconda

    - name: osx
      osx_instance:
        image: high-sierra-xcode-9.4.1
      conda_script:
        - curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > install.sh
        - bash ./install.sh -b -p $HOME/conda
      env:
        PATH: "$HOME/conda/bin:$PATH"

  install_script:
    - python -m pip install --retries 3 --upgrade pip
    - pip install --retries 3 -r requirements.txt

  check_script:
    - pip list
    - python -c "import napari"

  test_script:
    - pytest -v
```
