### ISSUE TITLE
Embedded env. vars. in gce_instance: image_name

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#191]
I'd like to be able to generate images from one task, then utilize them in another.  For example, I'd like to use this task to pass a build-specific suffix down to packer for image generation:

```yaml
build_images_task:

    only_if: >-
        $CIRRUS_BRANCH != 'master' &&
        $CIRRUS_CHANGE_MESSAGE =~ '.*\*\*\*\s*CIRRUS:\s*BUILD\s*IMAGES\s*\*\*\*.*'

    # VMs created by packer are not cleaned up by cirrus, must allow task to complete
    auto_cancellation: $CI != "true"

    env:
        BUILT_IMAGE_SUFFIX: "-${CIRRUS_REPO_NAME}-${CIRRUS_BUILD_ID}"

    gce_instance:
        image_name: "${IMAGE_BUILDER_IMAGE_NAME}"
        scopes:  # required for image building
            - compute
            - devstorage.full_control

    environment_script: $SCRIPT_BASE/setup_environment.sh
    build_vm_images_script: $SCRIPT_BASE/build_vm_images.sh
```

Then use the suffix in a dependent task to test using the new images:

```yaml
test_images_task:
    only_if: >-
        $CIRRUS_BRANCH != 'master' &&
        $CIRRUS_CHANGE_MESSAGE =~ '.*\*\*\*\s*CIRRUS:\s*BUILD\s*IMAGES\s*\*\*\*.*'

    depends_on:
        - "build_images_task"

    env:
        BUILT_IMAGE_SUFFIX: "-${CIRRUS_REPO_NAME}-${CIRRUS_BUILD_ID}"

    gce_instance:
        matrix:
            image_name: "fedora-29-${BUILT_IMAGE_SUFFIX}"
            image_name: "fedora-28-${BUILT_IMAGE_SUFFIX}"
            image_name: "ubuntu-18-${BUILT_IMAGE_SUFFIX}"

    setup_environment_script: $SCRIPT_BASE/setup_environment.sh
    unit_test_script: $SCRIPT_BASE/unit_test.sh
    integration_test_script: $SCRIPT_BASE/integration_test.sh
``` 

I tried running this, and the images build fine, but then Cirrus returns an error similar to:

```
Failed to start: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/project-id-1234/global/images/fedora-28-${CIRRUS_REPO_NAME}-${CIRRUS_BUILD_ID}'. The referenced image resource cannot be found.
```
