### ISSUE TITLE
Expression to check changest

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#197]
It will be nice to have `changedFilesContain` function that can be used in expressions to run some tasks only on changes to certain files. For example, run lint only on changes to source files:

```yaml
lint_task:
  only_if: changedFilesContain('*.js')
  ...
```

For PRs changed files will be calculated agains the base branch. For others, [`CIRRUS_LAST_SUCCESSFUL_CHANGE`](https://github.com/cirruslabs/cirrus-ci-docs/issues/196) will be used for the diff.

`changedFilesContain` name is up for a discussion. 😅
