### ISSUE TITLE
Cirrus test succeeding when it should have failed.

### ISSUE THREAD

**Issue by gspencergoog** [cirruslabs/cirrus-ci-docs#20]
In [this Cirrus run](https://cirrus-ci.com/task/5397535736725504), the test failed, but the run succeeded.

Now, there is a bug in this script (it has Bash line with the "export" when it should do the Windows equivalent), but even if that wasn't there, I think it might have done the same thing.

I think the root of the problem is that Cirrus is prefixing a "call " for each line in the script, and in the `.cirrus.yml` file, an extra blank line is getting added to the test_all_script, so Cirrus does `call` on an empty line, which returns success, allowing the build to "succeed" when it didn't, really. I'm quite sure that test.dart is returning a 1 as an exit code.

```yml
task:
  name: tool_tests-windows
  env:
    SHARD: tool_tests
  windows_container:
    image: cirrusci/windowsservercore:2016
    os_version: 2016
    cpu: 4
  env:
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\flutter sdk"
  git_fetch_script: git fetch origin
  setup_script:
    - bin\flutter.bat config --no-analytics
    - bin\flutter.bat update-packages
    - git fetch origin master
  test_all_script: |
    export TEST_COMMIT_RANGE="$(git merge-base --fork-point FETCH_HEAD HEAD || git merge-base FETCH_HEAD HEAD)..HEAD"
    bin\cache\dart-sdk\bin\dart.exe -c dev\bots\test.dart

```

Cirrus should probably either not add "call" to each line, or it should strip blank lines from the script.
