### ISSUE TITLE
Run tests on all supported platforms?

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-ci-docs#207]
# Question

I'm trying to figure out how to use Cirrus CI for testing a single project on all of:

- FreeBSD
- Linux
- macOS
- Windows

However, the examples don't seem to cover using even two platforms simultaneously, and searching online hasn't really provided much help.

Where do I even start?

**Comment by RDIL** [comment]
Hey @duckinator ,

To use different OSes in parallel, it depends on if you want to do it in the same task, or different tasks.

If you want to do it in the same task, `matrix` modifications can help out a ton.  You can read up [here](https://cirrus-ci.org/guide/writing-tasks/#matrix-modification).  An example could be:
```yaml
test_task:
  # note: the images specified here may not work, this is just to show off how to actually do this.  
  matrix:
    # DockerLinux:
    - container:
         image: coolimage:verson
    # macOS:
    - osx_instance:
         image: Mojave_xcode_10.13
    # windows:
    - windows_instance:
         image: windowsservercore
  script: ./dowhatever.sh

Or in different tasks:
```yaml
 macOS_test_task:
  osx_instance:
    image: somemacimage
```
and so on, so forth.  
If this doesn't fully answer your question, don't hesitate to leave me a reply :)

P.S. all images mentioned here were made up and may not work, see different guides for what images you can use: [macOS](https://cirrus-ci.org/guide/macOS/#list-of-available-images), [FreeBSD](https://cirrus-ci.org/guide/FreeBSD/#list-of-available-images), [Windows](https://cirrus-ci.org/guide/windows/#os-versions) (DockerLinux is just any name of any Docker image you want to use)

**Comment by fkorotkov** [comment]
Hey @duckinator, you can define multiple tasks in a single `.cirrus.yml` file like in an example [here](https://cirrus-ci.org/guide/writing-tasks/). You'll end up with something like:

```
task:
  name: Tests (Linux)
  container:
    image: ...
  tests_script: ...

task:
  name: Tests (Windows)
  windows_container:
    image: ...
  tests_script: ...

task:
  name: Tests (FreeBSD)
  freebsd_instance:
    image: ...
  tests_script: ...

task:
  name: Tests (macOS)
  osx_instance:
    image: ...
  tests_script: ...
```
