### ISSUE TITLE
Docker and macOS

### ISSUE THREAD

**Issue by mposa** [cirruslabs/cirrus-ci-docs#213]
# Question

Is Docker supported with the macOS builds? If not, is there another recommended path for a build system with significant package dependencies? Thanks.

**Comment by fkorotkov** [comment]
Docker requires nested virtualization to properly work. The latest version of Anka virtualization that Cirrus is using for macOS builds got nested virtualization support but in my experiments it was pretty unstable...

Could you please tell me a little bit more about your project and what are you trying to achieve?

**Comment by mposa** [comment]
At a high-level, the project is an open source robotics research library. (https://github.com/DAIRLab/dairlib). We build with bazel, and as we depend on Drake (https://github.com/RobotLocomotion/drake), have a lengthy dependency list. At least with the Ubuntu build, installing bazel and the required packages was fairly time consuming.

I have not tried adding a vanilla macOS CI build, but maybe the setup time is more manageable there.

**Comment by RDIL** [comment]
@mposa possible workaround:
```
task:
  name: MacOS Test
  osx_instance:
    # put osx image here
  prep_script: brew install docker
  script: docker info
```
