### ISSUE TITLE
Description Support

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#217]
# Description

Support a syntax that puts a custom sentence below the task name on the site that describes what the task does.  Ex:

```yaml
test_task:
  yarn_script:
    - yarn
    description: Install dependencies
```

# Context

Thought it might be handy.
