### ISSUE TITLE
`Always` instructions break extensions after

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#227]
# Expected Behavior

Stuff in an always block should be executed even on failure, and that is it.

# Real Behavior

The expected behavior happens, but **stuff that is stated after (and outside) of the always block.**
Example:
```yaml
test_task:

  # This will PASS:
  hello_world_script: |
   echo "hi world"

  # This will FAIL:
  hey_i_will_fail_script: |
    isgfidhighdfighdshg

  always:
    # This should ALWAYS be run
    some_script: echo "you will always be seeing me"

  # This should NOT ALWAYS be run
  reeee_script: echo "but you should only see me in passes, but no! bug ahoy"
```

# Related Info

- [ ] Website issue
  - Link to page:
- [X] Task issue
  - OS: Any
  - Task name: in the example it is `test_task`
  - Script/cache name (if applies): in the example it is `some_script` and `reeee_script`
