### ISSUE TITLE
Seemingly invalid YAML in examples

### ISSUE THREAD

**Issue by phyber** [cirruslabs/cirrus-ci-docs#232]
# Question

So, I know your examples work, since I'm using them in some of my projects, however, your YAML looks invalid, and a brief read of the YAML spec also seems to suggest it's invalid.

For example:

```yaml
---
task:
  name: 'Example'
  freebsd_instance:
    matrix:
      image: 'freebsd-12-0-release-amd64'
      image: 'freebsd-11-2-release-amd64'
```

Cirrus will parse this just fine, and run the `task` on each of those images, however, those `image` keys are not unique. If you load this in any regular YAML parser, you'll end up with a different hash than what Cirrus sees (one of the `image` entries will be clobbered)

I haven't tried the following example, but I assume it also works on Cirrus based on part of the documentation even though the `task` keys are not unique and will clobber each other in any regular YAML parser.

```yaml
---
task:
  name: 'ExampleA'
  etc: ~

task:
  name: 'ExampleB'
  etc: ~
```

Do you have any plans to fix this? YAML can already be weird enough without things like this further muddying the waters. Further, due to this style of YAML, it's not possible (at least, not easily) to generate a Cirrus CI config programmatically for those that might need to (hash keys are unique, etc).

It would also be nice if there was a reference for your YAML schema. You have documentation on [writing tasks](https://cirrus-ci.org/guide/writing-tasks/), but it's more of a list of examples than an in depth document.  See the excellent [configuration reference](https://circleci.com/docs/2.0/configuration-reference/#section=configuration) that CircleCI has for the style of reference documentation that would really benefit Cirrus. Concourse has similar documentation.

It would be great to know what is syntactic sugar and what isn't. For example:

You explain the following sugar on the `task` configuration.

```yaml
---
# Sugar
example_task:
  things: ~

# No sugar
task:
  name: 'example'
  things: ~
```

Later on, you introduce the `script` instruction as:

```yaml
---
# Approximation of your example
example_task:
  compile_script: 'true'
  check_script:
    - 'true'
```

However, is the `name` entry available here as well? The `script` instruction seems to be following the same convention as `task`, but the documentation mentions nothing. Is the `name_script` just sugar for something like the following?

```yaml
---
task:
  name: 'example'
  script:
    name: 'compile'
    command: 'true'
  script:
    name: 'check'
    command:
      - 'true'
```

The same question goes for the other `*_instruction` methods that you have.

Finally, thanks for Cirrus CI. It's great to have someone providing FreeBSD CI instances 👍

**Comment by fkorotkov** [comment]
Agreed that documentation should prefer valid syntax rather than more human readable. For example, your matrix example is equal to:

```yaml
task:
  name: 'Example'
  freebsd_instance:
    matrix:
      - image: 'freebsd-12-0-release-amd64'
      - image: 'freebsd-11-2-release-amd64'
```

As for naming, documentation pretty clearly mentions the two ways of naming: `foo_task` or `name: foo`. Documentation should mentioned that it doesn't work for instructions the same way.

There is also a [JSON schema for `.cirrus.yml` files](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/cirrus.json) that you can use for validation. Many editors support it so you can get some assistance and validation when modifying config files.

Not sure about how to create a similar configuration reference. For example, Cirrus can specify [execution behaviour for instructions](https://cirrus-ci.org/guide/writing-tasks/#execution-behavior-of-instructions), some of the task fields can be configured outside of `task` entity for sharing:

```yaml

evn:
  NAME: Fedor

foo_task:
  # will have $NAME
  ...

bar_task:
  # will have $NAME
  ...
```

All this syntactic things were added for humans to make the config more concise.  

Created #233 which improves a few things and IMO is a good compromise. PTAL and let me know what do you think.

**Comment by phyber** [comment]
Thanks, this is great. Valid YAML in the documentation is much appreciated, as is the link to the YAML schema.

So, my next question is, if I have two tasks, the following sugar is valid

```yaml
---
a_task:
  things: ~

b_task:
  more_things: ~
```

Is there a valid YAML equivalent of this?

**Comment by fkorotkov** [comment]
You mean without the `(.*)_task` syntax? Unfortunately, not at the moment. If you want syntax that looks like this:

```yaml
tasks:
  - name: a
     things: ~
  - name: b
     more_things: ~
```

I think we can extend the parser to support it.  Might be useful for generators, as you mentioned.
