### ISSUE TITLE
Exclude paths in artifacts

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#235]
# Description

A syntax to EXCLUDE some files from the upload.  For example

cool_artifacts:
  path: directory1/
  except: directory1/directory2

# Context

* saves space
* speeds up uploading

# Anything Else
Nope

**Comment by fkorotkov** [comment]
I think in this case you can either use multiple paths:

```yaml
junit_artifacts:
  paths:
    - directory1/directory1
    - directory1/directory3
```

Or add a `cache_cleanup` script before uploading the artifacts to remove unnecessary files.
