### ISSUE TITLE
Caching question

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#236]
# Question

For gradle, the example says to do `rm -rf ~/.gradle/caches/$GRADLE_VERSION`.  Is the value of `GRADLE_VERSION` equal to the version on the *Docker image*, or the *wrapper*?

My `/gradle/wrapper/gradle-wrapper.properties`:
```gradle
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.0.2-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```
The `gradle:jdk8` points to gradle 5.3, which my project doesn't use.  So would gradle_version env variable be 5.3 or 4.0.2?

**Comment by fkorotkov** [comment]
It will be `5.3`

**Comment by RDIL** [comment]
But wouldn't I want to delete 4.0.2 since it is used as the version to run the build daemon with?

**Comment by fkorotkov** [comment]
Upload cache instruction should report which files were changed in case of a cache invalidation. Just check if you see something in `~/.gradle/caches/$GRADLE_VERSION`

**Comment by RDIL** [comment]
Yeah,

**Comment by RDIL** [comment]
```yaml
SHA for /home/gradle/.gradle/caches is '6c205a0d2141aea1bad77f682e16175ca3849de6933d4dec89287160ea18fcea'
Cache gradle has changed!
List of changes for /home/gradle/.gradle/caches:
modified: 4.0.2/scripts/6q01go0enqos3cvvyqmcko18n/cp_settings/cp_settings19e4e623dd9ac0dbfc884b02c3795cb2/cache.properties
modified: 4.0.2/scripts-remapped/settings_a93r2s2sth12ghlioaa8sst89/6q01go0enqos3cvvyqmcko18n/cp_settings19e4e623dd9ac0dbfc884b02c3795cb2/cache.properties
modified: 4.0.2/scripts-remapped/build_8724zmd79chd61ckga2d9fx59/fpuhqxrpb58fvu0xea5db4vb/proj6458c755c7c91a5b2d520cd0bd67ce64/cache.properties
modified: 4.0.2/scripts/fpuhqxrpb58fvu0xea5db4vb/cp_proj/cp_proj19e4e623dd9ac0dbfc884b02c3795cb2/cache.properties
modified: minecraft/deobfedDeps/compileDummy.jar
modified: 4.0.2/scripts-remapped/settings_a93r2s2sth12ghlioaa8sst89/6q01go0enqos3cvvyqmcko18n/settings19e4e623dd9ac0dbfc884b02c3795cb2/cache.properties
modified: 4.0.2/scripts/6q01go0enqos3cvvyqmcko18n/settings/settings19e4e623dd9ac0dbfc884b02c3795cb2/cache.properties
modified: minecraft/deobfedDeps/providedDummy.jar
modified: 4.0.2/fileHashes/fileHashes.bin
modified: 4.0.2/scripts/fpuhqxrpb58fvu0xea5db4vb/proj/proj6458c755c7c91a5b2d520cd0bd67ce64/cache.properties
modified: 4.0.2/scripts-remapped/build_8724zmd79chd61ckga2d9fx59/fpuhqxrpb58fvu0xea5db4vb/cp_proj19e4e623dd9ac0dbfc884b02c3795cb2/cache.properties
gradle cache size is 217Mb.
Uploading cache gradle...
```
should I specifically `rm -rf` the 4.0.2 directory?
