### ISSUE TITLE
New task syntax

### ISSUE THREAD

**Issue by phyber** [cirruslabs/cirrus-ci-docs#252]
# Description

As discussed in #232 a new syntax for `tasks` would be useful.

# Context

It's difficult to generate valid YAML at the moment. Adding a `tasks` key also groups our tasks together in the YAML naturally, making navigating complex configurations slightly easier.

# Anything Else

Exact comment: https://github.com/cirruslabs/cirrus-ci-docs/issues/232#issuecomment-480026455

Example:

```yaml
tasks:
  - name: a
    things: ~
  - name: b
    more_things: ~
```
