### ISSUE TITLE
Support ignoring files in cache upload

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#262]
# Description

It would be nice if we could ignore uploading new caches if certain files are changed.

# Context

In my project, `~/.gradle/caches` is always being reuploaded because `minecraft/deobfedDeps/compileDummy.jar` and `minecraft/deobfedDeps/providedDummy.jar` are always changed. I can't delete the file as it will fail the build, and constant reuploads slow down the build.

# Anything Else

Proposed syntax:
```yaml
gradle_cache:
  folder: ~/.gradle/caches
  fingerprint_script: cat build.gradle && cat settings.gradle
  populate_script: gradle setupCiWorkspace
  ignore_changes:
    - file1.jar
    - file2.jar
```
