### ISSUE TITLE
Combine artifacts of tasks with the same name

### ISSUE THREAD

**Issue by carlwgeorge** [cirruslabs/cirrus-ci-docs#265]
# Question

I'm happy to see that it's now possible to [download all artifacts from a task](https://github.com/cirruslabs/cirrus-ci-docs/issues/254).  However, using this with a matrix modification doesn't give the expected result.  [Here is my configuration](https://github.com/iusrepo/cello/blob/0ed49db6b67ea43bf0808e72e9519bbd6bd286ce/.cirrus.yml).  That builds RPM artifacts for both CentOS 6 and 7 using a matrix modification.  [Both tasks share the same `rpmbuild` name](https://cirrus-ci.com/build/5414389308981248).  Downloading using the [documented link format](https://api.cirrus-ci.com/v1/artifact/github/iusrepo/cello/rpmbuild/rpms.zip) gives me a zip file that contains artifacts from the `centos:7` permutation, but not the `centos:6` permutation.  My assumption here is that the `centos:7` permutation finished last, so it's the literal latest for the `rpmbuild` task.

Can all the artifacts from a matrix build be combined somehow?

Another possibility would be to have matrix modifications modify the task name, so that the download link can be unique for each matrix permutation.  In this case that would result in two tasks named `rpmbuild_centos_6` and `rpmbuild_centos_7` (or similar).

**Comment by fkorotkov** [comment]
Workaround for now:

```yaml
task:
  env:
    matrix:
      CENTOS_VERSION:6
      CENTOS_VERSION:7
  name: "rpmbuild_$CENTOS_VERSION"
  container:
    image: centos:$CENTOS_VERSION
```
