### ISSUE TITLE
Node Selection for GKE

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#268]
# Description

It will be nice to allow to specify labels for node selection for GKE integration.

# Context

It will allow to target node pools with SSDs, GPUs, etc.

```yaml
gke_container:
  image: gradle:jdk8
  cluster_name: cirrus-ci-cluster
  zone: us-central1-a
  node_selector_terms:
    - key: "kubernetes.io/hostname"
       operator: "In"
       values: "gke-test-cluster-default-pool-926ddf80-f166"
```
