### ISSUE TITLE
Container Environment Variable

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#276]
# Description

`$CIRRUS_CONTAINER` -
If build running on FreeBSD or Darwin, set it to `""`
If build is running on DockerLinux or Windows, set the variable to what it is defined as in the config.

## Examples:
* `echo $CIRRUS_CONTAINER` => `image: ruby:latest`
* `echo $CIRRUS_CONTAINER` => `image: windowsservercore:2019`

# Context

Would be helpful for test customization

**Comment by fkorotkov** [comment]
You can do yourself:

```yaml
task:
  env:
    CIRRUS_CONTAINER: "ruby:latest"
  container:
    image: $CIRRUS_CONTAINER
```

Don't see a need in a builtin variable. 🤷‍♂
