### ISSUE TITLE
Ability to name matrix jobs

### ISSUE THREAD

**Issue by Jnewbon** [cirruslabs/cirrus-ci-docs#278]
# Description

When using matrices the task spawn off multiple identical named jobs that are hard to distinguish without drilling deep into the build logs. Having the ability to name each job in the matrix would solve this.

**Comment by RDIL** [comment]
Hey @Jnewbon,
Welcome to Cirrus CI!
This feature can already be achieved by doing the following:
```yaml
task:
  matrix:
    - name: task_1
      some_script: script1
    - name: task_2
      some_other_script: script2
```

**Comment by fkorotkov** [comment]
Plus in the UI there should be unique labels to distinguish the tasks. For example,

```
test_task:
  env:
    matrix:
      - SHARD: 1
      - SHARD: 2
```

will end up with `test SHARD:1` and `test SHARD:2` in the UI.
