### ISSUE TITLE
ability to run docker-in-docker builds on gke cluster

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#286]
We want to build docker images using cirrus.
However we don't want to use raw VMs per job since spawning them is simply quite slow compared to simply spinning up GKE containers and I also don't want to deal with VM image builds etc..
I'm already *theoretically* able to build containers in GKE using the setup below:
```yaml
gke_container:
  image: my-cd-tools:latest
  cluster_name: my-gke-cluster
  zone: us-west1-c
  namespace: cirrus-ci
  cpu: 2
  memory: 4Gb
  additional_containers:
    - name: docker-daemon
      image: docker:18.06-dind
      port: 2375
```
 Note the cd-tools image above contains the docker client CLI amongst a few other things. 
 In the build job itself I'm setting the environment variables:
```yaml
DOCKER_HOST: tcp://localhost:2375
DOCKER_DRIVER: overlay2
```

Now the only missing piece would be the ability to run the docker-daemon container with:
```yaml
securityContext:
  privileged: true
```
(i.e. setting this attribute on the container in the k8s pod).

Do you think it would be possible to add a flag to cirrus to allow running the container in privileged mode (not on the community cluster of course, but on self hosted clusters)?

**Comment by fkorotkov** [comment]
Just deployed the improvement/ You can use it like this (note the name is `docker` since it can't contain `-`):

```yaml
additional_containers:
    - name: docker
      image: docker:18.06-dind
      privileged: true
      port: 2375
```
