### ISSUE TITLE
Glob issues

### ISSUE THREAD

**Issue by avowkind** [cirruslabs/cirrus-ci-docs#298]
Container is only running half my tests.  
so I added this task

```yaml
ls_task:
  test_script: ls **/*.spec.js
```

it matches a single file - the first one found.  while on my mac it matches about 20 files in different folders.

locally: 
[glob.log](https://github.com/cirruslabs/cirrus-ci-docs/files/3210167/glob.log)

on CI
ls **/*.spec.js
__tests__/about.spec.js

.cirrus.yml

```yaml
container:
  image: node:latest

lint_task:      
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci

  test_script: npm run lint

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script: npm test

ls_task:
  test_script: ls **/*.spec.js
````
