### ISSUE TITLE
env variables in matrix don't override those at task level

### ISSUE THREAD

**Issue by DanTup** [cirruslabs/cirrus-ci-docs#30]
Not sure if this is a bug, but it caught me out and seems counter-intuitive. (Also, not sure if this repo is the right place, it's not really a docs issue nor a website issue).

Given this config:

```yaml
task:
  env:
    SHARD: tests
  test_all_script:
    - bin\cache\dart-sdk\bin\dart.exe -c dev\bots\test.dart
  matrix:
    - name: tests-windows
      env:
        SHARD: tests
    - name: tool_tests-windows
      env:
        SHARD: tool_tests
```

The SHARD env variable is set to `tests` for both builds, despite the `matrix`. In this case it's redundant at the top level, however if you wanted to set an env variable for all items in the matrix except one, it'd be convenient to write it this way (and only "override" it in the matrix entry you need to).
