### ISSUE TITLE
MSBuild and cmake

### ISSUE THREAD

**Issue by robertguetzkow** [cirruslabs/cirrus-ci-docs#300]
# Question

I tried to get MSBuild and cmake running. Not entirely sure were the problem is since the current handling of env vars and chocolatey doesn't make this particularly easy to debug. Even if I set the path to the MSBuild.exe by hand, it seems that cmake can't find all components necessary to build. Any ideas?

The version below at least managed to detect which SDK to use, `choco install -y visualstudio2017buildtools` didn't work at all after a successful installation.

.cirrus.yml:
```
Windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $PATH;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Program Files\CMake\bin
  prepare_script: choco install -y cmake && choco install -y microsoft-visual-cpp-build-tools && mkdir build
  configure_script: cd ./build && cmake -G "Visual Studio 14 2015 Win64" ..
  build_script: cmake --build ./build --config Release
```

output:
```
-- Selecting Windows SDK version  to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:
    MSBuild.exe
  to get the value of VCTargetsPath:
    The system cannot find the file specified
-- Configuring incomplete, errors occurred!
```
