### ISSUE TITLE
Human Readable Config Schema

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#334]
# Description

Need to generate a human readable schema similar to the JSON one: http://json.schemastore.org/cirrus

Should describe all the required fields and optional fields as well as "combinable" fields like `env`:

```yaml
env:
  FOO: foo

task:
  env: # will be combine with the one above
    BAR: bar 
```
