### ISSUE TITLE
Explain the interaction between depends_on and task names

### ISSUE THREAD

**Issue by gspencergoog** [cirruslabs/cirrus-ci-docs#34]
In the docs, the description of the `depends_on` feature of the config file uses an example that has no names, only named tasks.

```yaml
lint_task:
  script: yarn run lint

test_task:
  script: yarn run test

publish_task:
  depends_on: 
    - test
    - lint
  script: yarn run publish
```

But it appears that there is another way to specify the `depends_on` names.

```yaml
task:
  name: lint
  script: yarn run lint

task:
  name: test
  script: yarn run test

task:
  name: publish
  depends_on: 
    - test
    - lint
  script: yarn run publish
```

And it's not really clear how to combine the two:

```yaml
lint_task:
  script: yarn run lint
  matrix:
    - name: lint_foo
      env:
        SOMETHING = foo
    - name: lint_bar
      env:
        SOMETHING = bar

task:
  name: test
  script: yarn run test

task:
  name: publish
  depends_on: 
    - test
    - lint_task
  script: yarn run publish
```

Can I say something depends on just the `lint_foo` task (it doesn't appear to work, at least)?

It appears that if I leave the task name as just `task`, then it uses the name: for dependencies, but if I set it to `lint_task`, then it uses `lint` as the name.  Is there any way to say something like `depends_on: lint_task:lint_foo`?

(I'd also note that some YAML parsers don't like that there are multiple tags with the same name at the same level, but that's really academic: it seems to work fine as long as there are names)
