### ISSUE TITLE
Is a cached build using 'dockerfile' available for Windows containers?

### ISSUE THREAD

**Issue by morganwillcock** [cirruslabs/cirrus-ci-docs#345]
# Question

Hi,

The documentation doesn't seem to cover a cached Docker build for CI purposes when the container build needs to be using Windows containers.

I've tried this:
<pre>docker_builder:
  platform: windows
  os_version: 2019

ci_task:
  container:
    dockerfile: ci/windows/Dockerfile</pre>

...but this still tries to use Linux.
https://cirrus-ci.com/task/5507891094618112

Is a cached CI build supported for Windows containers?

Thanks,
Morgan

**Comment by fkorotkov** [comment]
Yes, you should use `windows_contianer` intance though:

```yaml
ci_task:
  windows_container:
    dockerfile: ci/windows/Dockerfile
    os_version: 2019
```
