### ISSUE TITLE
Task Execution Dependencies on a docker_builder task

### ISSUE THREAD

**Issue by rraub** [cirruslabs/cirrus-ci-docs#350]
# Expected Behavior

Given:
```
docker_builder:
  name: build_image
  script: docker build .

deploy_task:
  depends_on: 
    - build_image
  script: ./deploy.sh
```
I would expect the deploy task to wait for the `build_image` task to finish before starting.

# Real Behavior

Both tasks start at the same time.

# Related Info

- The examples in https://cirrus-ci.org/guide/writing-tasks/#task-execution-dependencies do not include docker_builder tasks, so I am assuming this is either a feature that hasn't been implemented or there is a bug in it.
