### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#360]
# Description

It will be nice to support option to have GPUs attached to containers.

```yaml
container:
  image: nvidia/cuda:10.0-runtime-ubuntu18.04
  cpu: 4
  memory: 12G
  gpu: 2
  gpu_type: nvidia-tesla-v100 # do we need the choice?
```

# Context

See Twitter conversation here: https://twitter.com/acberceanu/status/1151884558725459968

# Anything Else

[Free limits](https://cirrus-ci.org/faq/#are-there-any-limits) and [compute credits](https://cirrus-ci.org/pricing/#compute-credits) pricing are TBD

Should be there an option to choose between different GPU like `nvidia-tesla-k80`, `nvidia-tesla-p100`, `nvidia-tesla-p4`, `nvidia-tesla-v100`, or `nvidia-tesla-t4`? Does it make sense for such workloads? 🤔
