### ISSUE TITLE
how to run a task only on pull request

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-docs#372]
I'd like to run a particular task only when it's a PR.
I understand there is the `CIRRUS_PR` variable but it's unclear to me how I can test for the existence of this variable using the built-in operators (https://cirrus-ci.org/guide/writing-tasks/#supported-operators) .

Could you please help me out here?

Thanks

**Comment by RDIL** [comment]
skip: CIRRUS_PR != ""

**Comment by fkorotkov** [comment]
```yaml
task:
  name: Only on PR
  skip: CIRRUS_PR != ""
  ...
```
