### ISSUE TITLE
Support KVM

### ISSUE THREAD

**Issue by ened** [cirruslabs/cirrus-ci-docs#397]
# Description

For integration testing on Android, it would be helpful to have a fast emulator running.
One choice is to start a x86 emulator. Unfortunately it requires hardware support and fails as below:

```
avdmanager create avd -n test -k "system-images;android-28;google_apis;x86"

$ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
statvfs('/home/cirrus/.android/avd/test.avd/snapshots/default_boot/ram.img') failed: No such file or directory
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
```

I will defer to the arm version but would ideally like x86 to run as it's significantly faster.

**Comment by fkorotkov** [comment]
The issue here is that for KVM-enabled emulator a container should be running in privileged mode. For community cluster it will be a security issue but theoretically it's possible to run if you are [bringing you own infrastructure](https://cirrus-ci.org/guide/supported-computing-services/).

At the moment I don't see a secure way of bringing it to community cluster. 😪

**Comment by ened** [comment]
Understood. It will probably not be an option for us then at the moment. 
Speaking of own infrastructure, could we possibly install a instance of Cirrus on our local build server?

**Comment by RDIL** [comment]
Right now, Cirrus can't be run on your own servers.

**Comment by fkorotkov** [comment]
@RDIL that's not true. Cirrus supports running on [your own infrastructure](https://cirrus-ci.org/guide/supported-computing-services/). On the founding ideas was to leverage modern clouds and compute services. Check [my blog post](https://medium.com/cirruslabs/core-principle-of-continuous-integration-systems-is-obsolete-8d926e17c721) for details.

@ened you can for example configure GKE and use privileged containers like this:

```yaml
task:
  gke_container:
    image: ...
    privileged: true
```

**Comment by RDIL** [comment]
I thought he meant running his own version of the cirrus backend

**Comment by fkorotkov** [comment]
In the context it seems the question was about Cirrus "Workers" that executed tasks in privileged containers. 🤷‍♂️

**Comment by ened** [comment]
Sorry for not being clear.

I was indeed referring to local infrastructure next door to where I'm sitting, in our office.

**Comment by fkorotkov** [comment]
Please follow #263 issue for this feature. 🙌 Right now it's not possible.

**Comment by fkorotkov** [comment]
I think I found a way how to make it work securely on community cluster. Will experiment this week.

**Comment by fkorotkov** [comment]
Hey @ened, you can now try an WIP support for KVM by simply adding `kvm: true` to your container definition. Here is a working example that I tested with:

```yaml
task:
  name: KVM
  container:
    image: cirrusci/android-sdk:29
    kvm: true
  accel_check_script:
    - sudo chown cirrus:cirrus /dev/kvm
    - emulator -accel-check
```

There are two caveats that the performance will be around 10% slower because of the additional virtualization plus such KVM-enabled containers starts a bit slower (in one minute rather then usual seconds). Feel free to test it and let me know what do you think. I hope you'll get some very impressive performance wins. 🤞

**Comment by fkorotkov** [comment]
Hey @ened, wanted to check with you if you had time to test out KVM-enabled containers?

**Comment by ened** [comment]
@fkorotkov this does not seem to work with Dockerfile's directly:

```
connected_check_task:
  name: Flutter driver test on Android
  container:
    dockerfile: .ci/Dockerfile
    cpu: 3
    memory: 4G
    kvm: true
```

?

**Comment by fkorotkov** [comment]
@ened it should work, the `Prebuild .ci/Dockerfile` task won't have KVM though.

**Comment by ened** [comment]
What is your suggestion on enabling KVM for a repo with a Dockerfile like shown?

**Comment by fkorotkov** [comment]
I'll take a look later today. Could you please add a link to a task where I can see kvm wasn't available?

**Comment by ened** [comment]
> I'll take a look later today. Could you please add a link to a task where I can see kvm wasn't available?

Sent on Discord.

**Comment by ened** [comment]
Dear @fkorotkov, thank you for your help with this issue. Really happy this works.

KVM works well, even for Dockerfile based setup.

Here is what we ended up with:

```
connected_check_task:
  name: Flutter driver test on Android
  only_if: $CIRRUS_BRANCH == "master" || CIRRUS_PR != ""
  env:
    API_LEVEL: 28
    TARGET: default
    ARCH: x86_64
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 4G
    kvm: true
  create_device_script:
    - echo no | avdmanager create avd --force --name "api-${API_LEVEL}" --abi "${TARGET}/${ARCH}" --package "system-images;android-${API_LEVEL};${TARGET};${ARCH}"
  start_emulator_background_script:
    - sudo chown cirrus:cirrus /dev/kvm
    - $ANDROID_HOME/emulator/emulator -avd "api-${API_LEVEL}" -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
```

It was important to set the `cpu:` count to a multiple of 2, as you mentioned. The error message was not clear for a cpu count of 3.

Also, the cirrus:cirrus user must own /dev/kvm for the emulator to start successfully.

Debugging was a bit hard as the _background_script would silently fail and not show the error message in the logs.

There is a remaining problem:

```
cd example
flutter drive --driver=test_driver/flutter_uploader_e2e_test.dart test_driver/flutter_uploader_test.dart
Running "flutter pub get" in example...                             5.1s
Using device Android SDK built for x86 64.
Starting application: test_driver/flutter_uploader_test.dart
"build/app/outputs/apk/app.apk" does not exist.
Running Gradle task 'assembleDebug'...                            741.7s (!)
✓ Built build/app/outputs/apk/debug/app-debug.apk.
adb: device 'emulator-5554' not found
Installing build/app/outputs/apk/app.apk...                         0.0s
Error: ADB exited with exit code 255
Performing Push Install
adb: error: failed to get feature set: device 'emulator-5554' not found
Application failed to start. Will not run test. Quitting.
```

However, this may be related to the App setup itself, so I will double check and open a new ticket. Thank you again.
