### ISSUE TITLE
CIRRUS_FORK Environment Variable

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#419]
It will be nice to have `CIRRUS_FORK` environment variable which will be set to `true` for forks and `false` for the original repository.

## Workaround

Right now as suggested by @ped7g in #418 `CIRRUS_REPO_OWNER` can be used as a workaround:

```yaml
task:
      name: task requiring decrypted variable
      only_if: $CIRRUS_REPO_OWNER == 'my-organization'
```
