### ISSUE TITLE
CIRRUS_WORKING_DIR default not working

### ISSUE THREAD

**Issue by kne42** [cirruslabs/cirrus-ci-docs#423]
I have not checked on other OSs, but this is at least applicable to windows builds

# Expected Behavior

`CIRRUS_WORKING_DIR` should have a default value of "`cirrus-ci-build` folder inside of a system's temporary folder" when not defined

# Real Behavior

it is undefined

**Comment by fkorotkov** [comment]
@kne42 could you please attache an example of such task where it happened?

**Comment by kne42** [comment]
here's a toy example

```yaml
task:
    windows_container:
        image: cirrusci/windowsservercore:2019
        os_version: 2019
    env:
         USING_CWD: $CIRRUS_WORKING_DIR\something
    test_script:
        - echo %CIRRUS_WORKING_DIR%
        - echo %USING_CWD%
```

it shows up as
```
$ echo %CIRRUS_WORKING_DIR%

$ echo %USING_CWD%
\something
```

**Comment by kne42** [comment]
so I guess a more accurate description is that the default is not properly set before evaluating environment variables

**Comment by kne42** [comment]
real world example: https://cirrus-ci.com/task/5739998471520256?command=separate#L46
```yaml
task:
  auto_cancellation: true

  env:
    matrix:
      PY_VER: "3.6"

  matrix:
    - name: windows
      windows_container:
        image: cirrusci/windowsservercore:2019
        os_version: 2019
      env:
        ANACONDA_LOCATION: $USERPROFILE\anaconda
        PATH: $PATH;ANACONDA_LOCATION\Scripts;ANACONDA_LOCATION
        # https://github.com/vispy/vispy/blob/v0.5.3/appveyor.yml#L44
        VISPY_GL_LIB: $CIRRUS_WORKING_DIR\opengl32.dll
        PYTHON_ARCH: 64
      system_script:
        # install OpenSSL
        - choco install -y openssl.light
        # install OpenGL
        - ps: Invoke-RestMethod -Uri https://raw.githubusercontent.com/vispy/vispy/v0.5.3/make/install_opengl.ps1 -Method Get -OutFile opengl.ps1
        - powershell ./opengl.ps1
        - ps: rm opengl.ps1
      separate_script:
        - dir
        - echo %VISPY_GL_LIB%
        - echo %CIRRUS_WORKING_DIR%
        - dir %CIRRUS_WORKING_DIR%
        - dir C:\Windows\system32
      conda_script:
        - choco install -y miniconda3 --params="'/D:%USERPROFILE%\anaconda'"
        - conda update -yn base conda
        - conda install -y python=%PY_VER%
        - pip install setuptools-scm

  install_script:
    # pip >= 19.0 crashes on Linux with Python 3.7
    - python -m pip install --retries 3 --upgrade "pip<19.0"
    - pip install --retries 3 -r requirements.txt
    - python setup.py develop

  check_script:
    - pip list
    - python -c "import napari; print(napari.__version__)"

  test_script:
    - pytest -v
```
