### ISSUE TITLE
Access image built by Dockerfile-as-environment

### ISSUE THREAD

**Issue by devxpy** [cirruslabs/cirrus-ci-docs#428]
Hey,

I want to push the images built by Dockerfile-as-container to docker hub.

For example,

```
my_task:
  container:
     dockerfile: Dockerfile
```

How do I obtain the image that will be built for `my_task`, and push it to docker hub?

**Comment by devxpy** [comment]
If not possible, how do I obtain the tag (e.g. `cirrus-ci-community/4f06007500a6b5fd824769cfbd889b0a`) for that image, so I can tag and push the same myself?

**Comment by devxpy** [comment]
The docker image cache doesn't seem to work with this method. It takes a long time to pull the image.

**Comment by devxpy** [comment]
The following config,

```yaml
environment:
  RELEASE_IMAGE: pycampers/micropython:${CIRRUS_TAG:$CIRRUS_BRANCH}

docker_builder:
  name: "Build docker image"
  pull_script: docker pull $RELEASE_IMAGE
  build_script: docker build --cache-from $RELEASE_IMAGE -t docker-image .

stm32_task:
  depends_on:
    - "Build docker image"
  container:
    image: docker-image
  test_script:
    - ./ci-scripts/stm32.sh
```

fails with:

![image](https://user-images.githubusercontent.com/19492893/63710212-4e6cb300-c856-11e9-93f1-5547336423aa.png)
