### ISSUE TITLE
Installing yarn on the windows containers

### ISSUE THREAD

**Issue by teken** [cirruslabs/cirrus-ci-docs#43]
I'm trying to install yarn on your container so i can build my electron app for windows on a windows box. 
I have this code which i believe should install yarn and choco

```
  yarn_script:
    - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - choco install yarn -y
    - refreshenv
```

but when i run a yarn command later down the process i get this error.
```
Unable to initialize device PRN
Cache miss for node_modules-284aa9424480e687f821eb01e365288f7030e2212707d46087d362cd6ada17d6! Populating...
yarn : The term 'yarn' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At C:\Users\ContainerAdministrator\AppData\Local\Temp\scripts81855ad8681d0d86d1
e91e00167939cb.ps1:3 char:1
+ yarn install
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (yarn:String) [], ParentContains 
   ErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
Failed to execute populate script for node_modules cache!
```

**Comment by teken** [comment]
```
windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2016
  env:
    CIRRUS_SHELL: powershell
  yarn_script:
    - Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    - choco install yarn -y
    - refreshenv
  node_modules_cache:
    folder: node_modules
    fingerprint_script: print yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  publish_script: yarn run release

mac_task:
  osx_instance:
    image: high-sierra-xcode-9.4.1
  yarn_script:
    - brew install yarn
  environment:
    CSC_IDENTITY_AUTO_DISCOVERY: false
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  publish_script: yarn run release

linux_task:
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  build_script: yarn run build
  publish_script: yarn run release
```
