### ISSUE TITLE
Support Arbitrarily Repository Metrics

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#449]
# Description

In addition to #93 it will be nice to expose an ability for users to expose arbitrary metrics like code coverage, benchmark score, amount of TODOs, etc.

# Context

Cirrus can comment on PRs with comparison of such stats with the base of the PR. Plus expose badges.

Each stat should have properties like:
* `unit` to define if it's a percent or an absolute number
* `merge_strategy` to define how to merge stats with the same name from different tasks. Either `override` or `average` (which might be useful for benchmarking: run couple of tasks in parallel and take the average).

Syntax might look like this:

```yaml
on_success:
  metric:
    name: performance
    unit: seconds
    merge_strategy: average
    value_script: cat benchmarking/performance.txt
```
