### ISSUE TITLE
failed cleanup_before_cache_script of Gradle Caching Example

### ISSUE THREAD

**Issue by granoeste** [cirruslabs/cirrus-ci-docs#46]
I try gradle caching with reference to [Examples \- Cirrus CI](https://cirrus-ci.org/examples/#caching)
```
container:
  image: cirrusci/flutter:latest

check_task:
  gradle_cache:
    folder: ~/.gradle/caches
  check_script: gradle check
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
```

However, the following error has occurred. 

`find: '/home/cirrus/.gradle/caches': No such file or directory`

Why find can not find directories? rm is no problem...

What is causing the error?
