### ISSUE TITLE
fail using gce instances

### ISSUE THREAD

**Issue by williamtu** [cirruslabs/cirrus-ci-docs#494]
Hi,
Is there a example of .cirrus.yml file for using gce?

I'm following the doc
https://cirrus-ci.org/guide/supported-computing-services/
to create an instance on gcp.
One question I have is that
is $PROJECT_ID the same as image_project in below setup? Or once I create the $PROJECT_ID in my google cloud console, do I need to put it in .cirrus.yml file?

```
gcp_credentials: ENCRYPTED[d2a8b5db42decced1d2dede9f93b42be1e1a5a8bd3bcb8a1b01c65cee403460c0978ef402b7a0a4f8c139f01fbf0674f]

gce_instance:
  image_project: ubuntu-os-cloud
  image_name: ubuntu-1904-disco-v20190417
  zone: us-central1-a
  cpu: 2
  memory: 40GB
  disk: 20

task:
  env:
    DEPENDENCIES: automake libtool gmake gcc wget openssl
                  python3 py36-six py36-openssl py36-sphinx
    matrix:
      COMPILER: gcc 
      COMPILER: clang

  prepare_script:
    - sysctl -w kern.coredump=0
    - pkg install -y ${DEPENDENCIES}

  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} CFLAGS="-g -O2 -Wall"
                  MAKE=gmake --enable-Werror
```
But got an error saying 
Failed to start: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
Failed to stop: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

Is it due to something wrong with my gcp_credentials ?

**Comment by RDIL** [comment]
A few things right off the bat:
*  The stuff you are doing with putting things on multiple lines, for example in `configure_script`, instruction 2, that doesn't look right.  You would most likely put it on one line.  Same with `env.DEPENDENCIES`.  That also may be a good thing to inline, or use a `|` YAML block.
* I believe `matrix` is an array, so it would need to be:
```yaml
matrix:
  - COMPILER: gcc
  - COMPILER: clang
```

Hopefully, one of those two is the issue, which would make debugging a lot easier.
