### ISSUE TITLE
before_each script?

### ISSUE THREAD

**Issue by ened** [cirruslabs/cirrus-ci-docs#495]
# Question

Currently, my `.cirrus.yml` looks a bit like this:

```
  install_rbenv_script:
    - brew install rbenv ruby-build
  ruby_rbenv_cache:
    folder: /Users/anka/.rbenv/versions/$RUBY_VERSION
    fingerprint_script: echo $RUBY_VERSION
    populate_script:
      - eval "$(rbenv init -)"
      - rbenv install $RUBY_VERSION
  prepare_ruby_script:
    - eval "$(rbenv init -)"
    - rbenv global $RUBY_VERSION
    - gem install bundler
  bundle_cache:
    folder: vendor
    fingerprint_script: cat Gemfile.lock
    populate_script:
      - eval "$(rbenv init -)"
      - bundle install
      - bundle cache
  bundle_install_script:
    - eval "$(rbenv init -)"
    - bundle install
```

This is bound to be run on a OSX instance.
rbenv is important for us so that we can be sure the scripts (fastlane support scripts) run well and predictably.

Is there a way to let a single `eval "$(rbenv init -)"` stay persistent for all "further" tasks. Or, could we define a "before_each" block, which is then run by Cirrus **before** __script_ block that follow?

So, something like this:

```
  install_rbenv_script:
    - brew install rbenv ruby-build
  # now that rbenv is installed, load it and make it available for every following script
  before_each:
    - eval "$(rbenv init -)"
  ruby_rbenv_cache:
    folder: /Users/anka/.rbenv/versions/$RUBY_VERSION
    fingerprint_script: echo $RUBY_VERSION
    populate_script:
      - rbenv install $RUBY_VERSION
  prepare_ruby_script:
    - rbenv global $RUBY_VERSION
    - gem install bundler
  bundle_cache:
    folder: vendor
    fingerprint_script: cat Gemfile.lock
    populate_script:
      - bundle install
      - bundle cache
  bundle_install_script:
    - bundle install
```
