### ISSUE TITLE
no error log showing when using 

### ISSUE THREAD

**Issue by williamtu** [cirruslabs/cirrus-ci-docs#498]
# Question

Hi,
I'm using gcp to run my test, however, when it fails, there is no log showing up when clicking the "download full log"
```
HTTP ERROR 404
Problem accessing /v1/task/5113668034887680/logs/prepare.log. Reason:

    Not Found
```
Do I need to enable something to see the log file?
Thanks!
https://cirrus-ci.com/task/5113668034887680

**Comment by fkorotkov** [comment]
That's weird. I'm not sure why logs didn't show up but I can see that it will definitely fail since the standard ubuntu image doesn't have pip preinstalled. 

Seems like a transient issue but anyways I've added some additional logs to troubleshoot similar issues in the future.

**Comment by williamtu** [comment]
Hi,
I change my .cirrus.yml to first print something, but still no log showing up.
s.t like
```
task:
  env:
    DEPENDENCIES: bc gcc-multilib libssl-dev llvm-dev libjemalloc1 libjemalloc-dev \
                  libnuma-dev python3-sphinx libelf-dev selinux-policy-dev \
                  libunbound-dev libunbound-dev:i386 libunwind-dev python3-pip
    COMPILER: gcc 

  prepare_script:
    - cat /etc/lsb-release
    - sudo apt-get install -y ${DEPENDENCIES}
    - pip install --disable-pip-version-check --user six flake8 hacking
    - pip install --user --upgrade docutils
```
I'm hoping at least the prepare stage I can see a log file. But still show
https://cirrus-ci.com/task/4828748343410688
```
HTTP ERROR 404
Problem accessing /v1/task/4828748343410688/logs/prepare.log. Reason:

    Not Found
```
Is there something I have to enable on GCE?
