### ISSUE TITLE
platform specific test within a matrix?

### ISSUE THREAD

**Issue by tlambert03** [cirruslabs/cirrus-ci-docs#506]
# Question

I'm wondering if it's possible to have different platform specific commands or arguments within a script inside of a single `task` using `matrix` modifications?  or whether cmd.exe will usually require using a different task.

For example, `test_script` here fails on windows due to improper environment variable formatting of `$TEST_ARGS` ... while `%TEST_ARGS%` would fail on linux
```yml
task:
  matrix:
    - name: linux
      container:
        image: gcc:latest

    - name: windows
      windows_container:
        image: cirrusci/windowsservercore:2019
      env:
        TEST_ARGS: "-o qt_no_exception_capture=1"
      
  install_script:
    - pip install  -r requirements.txt

  another_script:
    #stuff

  test_script:
    - pytest $TEST_ARGS -v
```
(Assume there's more stuff and more conditions in the matrix such that writing a whole new task just to modify `TEST_ARGS` on windows end up duplicating a lot of code)
