### ISSUE TITLE
Exclude jobs from matrix

### ISSUE THREAD

**Issue by mmcc007** [cirruslabs/cirrus-ci-docs#510]
It's possible to create a matrix of 8 jobs using something like:
``` yaml
task:
  env:
    matrix:
      - API: 28
      - API: 27
    matrix:
      - ABI: x86_64
      - ABI: x86
    matrix:
      - GOO: default
      - GOO: google_apis
```
How do I exclude certain jobs like:
```bash
$API==28 && $ABI==x86 && $GOO==default
```
The only workaround I can find is to use allow_failures, but this kicks-off the job which I am trying to avoid.

**Comment by RDIL** [comment]
`only_if` is your friend there.

**Comment by mmcc007** [comment]
Thanks for fast response!

That works, but it includes jobs, not excludes them. Would be easier if there was a way to explicitly exclude jobs?

**Comment by RDIL** [comment]
Can you detail what you mean by exclude?

**Comment by mmcc007** [comment]
I have 8 jobs defined using a matrix. I want to exclude 1 job.

**Comment by RDIL** [comment]
By exclude do you mean just show as passing or without running...?

**Comment by fkorotkov** [comment]
You can probably wrap `only_if` condition in `!(...)` like this:

```yaml
only_if: !($API==28 && $ABI==x86 && $GOO==default)
```

🤔

**Comment by RDIL** [comment]
I [suggested that](https://github.com/cirruslabs/cirrus-ci-docs/issues/510#issuecomment-551247415) @fkorotkov

**Comment by mmcc007** [comment]
That seems to be working. Thanks for help. Closing

**Comment by fkorotkov** [comment]
@RDIL you suggested the opposite: to include a certain job. With `!(...)` it will be what @mmcc007 is looking for.

 @mmcc007, otherwise you'll need to explicitly list all of the 7 variants:

```
task:
  env:
    matrix:
      - API: 28
        ABI: x86_64
        GOO: default
      - API: 27
        ABI: x86_64
        GOO: default
      ....
```

**Comment by mmcc007** [comment]
Thanks.

BTW: for larger matrix would be nice if
```bash
$API$GOO$ABI == "27google_apisx86_64"
```
worked and placing on multiple lines like:
```yaml
  only_if: ! (($API$GOO$ABI == "28google_apisx86_64") ||\
              ($API$GOO$ABI == "27google_apisx86_64"))
```
But that's a nice-to-have.

**Comment by mmcc007** [comment]
Also would be nice if only_if could work by within the matrix instead of being required to be global:
```yaml
# only_if is ignored
task:
  matrix:
    - name: accel, 28-27
      container:
        image: cirrusci/flutter:latest
        cpu: 4
        memory: 10G
        kvm: true
      env:
        matrix:
          - API: 28
          - API: 27
        matrix:
          - ABI: x86_64
        matrix:
          - GOO: google_apis
        only_if: !($API == "27" && $ABI == "x86_64" && $GOO == "google_apis")
    - name: no accel, 25-24
      container:
        image: cirrusci/flutter:latest
        cpu: 4
        memory: 10G
      env:
        matrix:
          - API: 25
          - API: 24
        matrix:
          - ABI: armeabi-v7a
        matrix:
          - GOO: google_apis
        only_if: !($API == "24" && $ABI == "armeabi-v7a" && $GOO == "google_apis")
  install_emulator_script: sdkmanager "system-images;android-$API;$GOO;$ABI" > /dev/null
#  only_if: (! ($API == "27" && $ABI == "x86_64" && $GOO == "google_apis") || ($API == "24" && $ABI == "armeabi-v7a" && $GOO == "google_apis"))
```
Also a nice-to-have
