### ISSUE TITLE
Support mapping ports on additional_containers

### ISSUE THREAD

**Issue by mattlorey** [cirruslabs/cirrus-ci-docs#521]
# Description

When starting multiple additional_containers, be able to map the port

# Context

We want to be able to run two postgres instances in tests, but cannot since they both bind to port 5432

# Anything Else

Specify the local port and the port exposed in the container

```
    additional_containers:
      - name: postgres
        image: postgres:alpine
        port: 5432:5432
        env:
          ...
      - name: postgres
        image: postgres:alpine
        cpu: 0.5
        memory: 1G
        port: 5433:5432
        env:
          ...

```
