### ISSUE TITLE
Do Windows container support `cpu` and `memory`?

### ISSUE THREAD

**Issue by eksperimental** [cirruslabs/cirrus-ci-docs#522]
I see no effect (at least the cpu setting), and it doesn't error either in case they are not supported

```yaml
  windows_container:
    cpu: 8
    memory: 1500Mi
```
