### ISSUE TITLE
Add title/label field to tasks

### ISSUE THREAD

**Issue by eksperimental** [cirruslabs/cirrus-ci-docs#527]
# Description
Add a title/label field for tasks so we can fine-tune the name that would appear in the notification and reports, due to the limitations that depends_on has when having to refer to a task by its name. 

# Context

If it's desired to have a very specific name for each task that is created with a matrix, and we want to depend on these tasks, it is difficult to use the feature `depends_on`, having to sacrifice the name of the tasks in the report for a generic one plusthe list of ENV variables.

Adding  the label or title field solves this, because title is what depends_on is going to be based on, and label is just for showing it on GitHub and in the reports.

This Feature Request stems from the limitations encountered in this PR https://github.com/elixir-lang/elixir/pull/9585

# Code sample
```yaml
test_linux_task:
  matrix:
    - name: Linux stable
      label: Linux, ${OTP_RELEASE}, Ubuntu 14.04
      matrix:
        - env:
            OTP_RELEASE: OTP-22.1
        - env:
            OTP_RELEASE: OTP-21.3.8

    - name: Linux development
      label: Linux, OTP-${OTP_RELEASE}, development, Ubuntu 14.04
      depends_on: Linux stable
      allow_failures: true
      skip_notifications: true
      matrix:
        - env:
            OTP_RELEASE: master
        - env:
            OTP_RELEASE: maint
```
