### ISSUE TITLE
container/image-family matrix + artifact name collision results in 500 errors

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-ci-docs#541]
#  Background

This is the relevant snippet of my .cirrus.yml, as an example:

```
fedora_task:
  container:
    matrix:
      - image: fedora:29
      - image: fedora:30
  script: python3 -m check_versions
  json_artifacts:
    path: "source/*.json"
```

If you have a task which:

1. has a matrix of container images or image families,
2. stores artifacts, and
3. a script which generates the same filename

Then you wind up with a situation where two tasks (as visible in the web UI) have the same file. In this case, `source/fedora.json`.

# Expected Behavior

What should have happened is ... probably some kind of error in the web interface if this is noticed, I guess? Not entirely sure...

# Real Behavior

What ended up happening was I did `wget https://api.cirrus-ci.com/v1/artifact/build/5069241232916480/fedora/json.zip` and got a 500 error.

# Related Info

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: confirmed on DockerLinux and FreeBSD, but seems likely on all OSes
  - Build: https://cirrus-ci.com/build/5069241232916480
  - Task name: `fedora` (both of them)
  - Script/cache name (if applies): `script` + `json_artifacts`

**Comment by duckinator** [comment]
Testcase: https://github.com/duckinator/cirrus-ci-issue-541-testcase

.cirrus.yml:
```
fedora_task:
  container:
    matrix:
      - image: fedora:29
      - image: fedora:30
  script:
    - mkdir artifacts
    - cat /etc/os-release | grep PRETTY_NAME | cut -d '"' -f 2 > artifacts/name.txt
  names_artifacts:
    path: "artifacts/*"
```

then run:

```
wget https://api.cirrus-ci.com/v1/artifact/build/${build_id}/fedora/names.zip
```
