### ISSUE TITLE
Globally disable pipelines for irrelevant file changes and branches

### ISSUE THREAD

**Issue by swaldhoer** [cirruslabs/cirrus-ci-docs#547]
# Description

There are or can be a lot of files in a repository that should generally not trigger a rebuild<sup id="a1">[1](#f1)</sup>.

Currently cirrus supports the ``skip`` and ``only_if`` directive to run or skip a task. This has the disadvantage that it needs to be added to every task even if the affected files are the same. A simple solution to this problem is provided by e. g., Azure Pipelines or AppVeyor<sup id="a2">[2](#f2)</sup>: Just list the files and branches you do globally not want a CI trigger. But I think this approach can be improved as there are files that never requires cirrus to run (e. g., other CI services, git configs).

I think it would be good if cirrus would support the same as Azure and AppVeyor. What would be even greater to support some smart values like like :
``.cirrus.yml``
```yaml
trigger:
  branches:
    include:
      - master
      - dev*
    exclude:
      - not-so-good-branch
  files:
    include:
      - docs/**
      - src/*.py
    exclude:
      - xyz
      - $(DEFAULTS)  # maps to $(GIT_FILES) and $(OTHER_CI)
      - $(GIT_FILES)  # ignore .gitignore and .gitattributes and .mailmap
      - $(OTHER_CI)  # ignore Azure, Appveyor, Travis, ReadTheDocs
```

----

<b id="f1">1) Other CI Servies</b>[↩](#a1)
[Azure Pipeline triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml):
```yaml
# specific path build
trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - docs/*
    exclude:
    - docs/README.md
```

[AppVeyor skip_commits](https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only):
```yaml
skip_commits:
  files:
    - dir/*
    - dir/*.md
    - full/path.txt
    - another/dir/here/
    - '**/*.html'
```

[AppVeyor branches](https://www.appveyor.com/docs/branches/#white--and-blacklisting):
```yaml
branches:
  only:
    - master
    - production
  except:
    - /dev.*/     # You can use Regular expression to match multiple branch name(s)
    - playground
```

----
<b id="f2">2 Example of files that should not trigger a build</b>[↩](#a2)
- Other CI services
  - AppVeyor (``.appveyor.yml`` and ``appveyor.yml``)
  - Azure Pipelines (``azure-pipelines.yml``)
  - Travis CI (``.travis.yml``)
  - ReadTheDocs (``.readthedocs.yml``)

- Git
  - files ignored by git (``.gitignore``)
  - attributes (``.gitattributes``)
  - mail (``.mailmap``)
