### ISSUE TITLE
Idiomatic way of saying: create me a github release on tag push and upload some artifacts to it

### ISSUE THREAD

**Issue by am11** [cirruslabs/cirrus-ci-docs#562]
Currently, we are using [a script](https://github.com/wfurt/freebsd-bootstrap-cli/blob/f59591c37f06c343686bd0ad35f04616463ebff1/scripts/upload-github-release-asset.sh) and calling it from .cirrus.yml to (idempotently) create a GitHub release on tag push and upload artifacts to it. e.g. https://github.com/am11/freebsd-bootstrap-cli/releases/tag/v3.0.2.

💡 since GitHub release is a commonly used feature, it would be nice to have this ability build-in. so we could do something like this in .cirrus.yml:

```yml
release:
  on: $CIRRUS_TAG
  provider: github
  token: ENCRYPT['blah']
  artifacts: glob_pattterns
  name: <my-platform-triplet>
  type: {tar, zip, bzip2}
```

**Comment by RDIL** [comment]
Please see https://cirrus-ci.org/faq/#is-cirrus-ci-a-delivery-platform

**Comment by fkorotkov** [comment]
I think it might be handy to mark some of [Cirrus artifacts](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction) as GitHub Release artifacts and re-upload them to GitHub as well.

```yaml
binary_artifacts:
  path: "build/bin/*"
  github_asset: $CIRRUS_RELEASE != ''
```
