### ISSUE TITLE
How do I invoke docker-compose inside my docker container?

### ISSUE THREAD

**Issue by Hamada92** [cirruslabs/cirrus-ci-docs#563]
Hey guys, 

I have this config file: 

```
efficient_task:
  container:
    dockerfile: app/Dockerfile # my own customer docker file
    test_script: docker-compose exec web bundle exec rspec
```
the docker file is building successfully, but then how do I run my own test inside the docker image using docker compose? this is the command that runs my tests: 
`docker-compose exec web bundle exec rspec`

Thanks
