### ISSUE TITLE
Support multiple folders for caching

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#565]
# Description

Support multiple folders for caching if they have a common prefix path

# Context

Flutter has large binaries cached in its bin/cache/artifacts, bin/cache/dart-sdk, bin/cache/pkg. Will be useful to be able to do something like:

```yaml
artifacts_cache:
  folders: 
    - bin/cache/artifacts
    - bin/cache/dart-sdk
    - bin/cache/pkg
````

To ignore all other folders/files in `bin/cache`
