### ISSUE TITLE
Allow to disable cache re-upload

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#568]
# Description

Right now cache instruction always checks if there were any changes in the cached folder and re-uploads the cache. Some tools do store some timestamp and other useless information. Suggested option was to have a `cache_cleanup_script` to remove such files but sometimes it's too hard to figure all the files and just not very productive to spend time on it. Let's add `reupload_on_changes ` config option to [cache instruction](https://cirrus-ci.org/guide/writing-tasks/#cache-instruction):

```yaml
node_modules_cache:
  folder: node_modules
  reupload_on_changes: false # true by default
  fingerprint_script: cat yarn.lock
  populate_script: yarn install
```
