### ISSUE TITLE
build_arguments not escaped on the command line

### ISSUE THREAD

**Issue by Minoru** [cirruslabs/cirrus-ci-docs#571]
When using Docker image as an environment, one can specify additional arguments like so:

```yaml
container:
  dockerfile: docker/ubuntu_18.04-build-tools.dockerfile
  docker_arguments:
      # We need llvm-symbolizer from llvm-9-tools to demangle symbols in
      # sanitizer's reports
      cxx_package: clang-9
      cc: clang-9
      cxx: clang++-9
```

Each argument turns into a `--build-arg` on the command line.

However, if the value in `docker_arguments` [contains a space](https://github.com/newsboat/newsboat/commit/5b63a83be0664a1413303348bddec891bcc1a397#diff-0f7067c31caedf7df2739c9b07efa122R224):

```yaml
      cxx_package: "clang-9 llvm-9"
```

...the value [gets interpreted by the shell as two separate arguments](https://cirrus-ci.com/task/6312890294599680?command=build#L0), because the space is not escaped in any way. That leads to Docker build failing.

To get around this, [I had to use double-backslash](https://github.com/newsboat/newsboat/commit/2d8af03435560bae5b51134bf733a4edafefba99#diff-0f7067c31caedf7df2739c9b07efa122R227):

```yaml
      cxx_package: "clang-9\\ llvm-9"
```

Cirrus's code un-escapes the value once, leaving a single backslash there, and [pastes that into the command line verbatim](https://cirrus-ci.com/task/5828875531845632?command=build#L0); the shell interprets `clang-9\ llvm-9` as a single argument, and the build proceeds fine.

It'd be nice if Cirrus hid those details from us, and quoted all arguments before putting them onto the command line.
