### ISSUE TITLE
Question about files glob for `changesInclude`

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#583]
# Question

We have [Conditional Task Execution](https://cirrus-ci.org/guide/writing-tasks/#conditional-task-execution) with example like:

```yaml
lint_task:
  skip: "!changesInclude('.cirrus.yml', '*.js', '**/*.js')"
  script: yarn run lint
```

I'm confused by `'*.js', '**/*.js'` — does not `'**/*.js'` includes `'*.js'`? `./` should be covered by `**/`, I think.

The code of this function can be enormous for a few file extensions, like:

```yaml
lint_task:
  skip: "!changesInclude('.cirrus.yml', '*.rb', '**/*.rb', '*.yml', '**/*.yml', '*.ru', '**/*.ru')" # etc.
  script: yarn run lint
```

**Comment by AlexWayfer** [comment]
And if it even so, maybe we can use globs like this? 

```yaml
lint_task:
  skip: "!changesInclude('.cirrus.yml', '{,**/}*.js')"
  script: yarn run lint
```
