### ISSUE TITLE
gce_instance: add 'name' or 'display_name' field

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-ci-docs#589]
# Description

Requesting the addition of a `name` or `display_name` field to `gce_instance` (and possibly others as necessary)
```yaml
      gce_instance:
          matrix:
              - name: fedora-30
                image_name: fedora-30-with-long-identifier-blah-blah
```

# Context

In `matrix` context, task names include the `image_name`. In our case, image names include long identifiers that the developer doesn't care about. Having shorter names would make for easier scanning of full results:
```diff
- testing image:fedora-31-libpod-5940307564953600 name:remote
+ testing image:fedora-31 name:remote
```

**Comment by edsantiago** [comment]
In the github summary view:
![cirrus-long-names](https://user-images.githubusercontent.com/265639/75908067-adfbda80-5e06-11ea-8dc6-796a0eef1ad8.png)

(Screenshot taken from [libpod pr5387](https://github.com/containers/libpod/pull/5387))

**Comment by fkorotkov** [comment]
I see. Cirrus has some logic to determine this label to present in the UI. Cirrus get's all possible labels for a task and for each task with the same name determines a unique subset of these labels.

Right now you have something like:

```
testing_task:
  env:
    matrix:
      name: local
      name: remote
  gce_instance:
          matrix:
              - image_name: fedora-30-with-long-identifier-blah-blah
              - image_name: fedora-31-with-long-identifier-blah-blah
```

What you can do is to have `Fedora XX` in the task name:

task:
  matrix:
    - name: Testing Fedora 30
       gce_instance:
         image_name: fedora-30-with-long-identifier-blah-blah
    - name: Testing Fedora 31
       gce_instance:
         image_name: fedora-31-with-long-identifier-blah-blah
  env:
    matrix:
      name: local
      name: remote
```

See https://github.com/containers/libpod/pull/5394

**Comment by edsantiago** [comment]
Thank you! I had tried that; what I was missing was the `alias` directive, needed in our case because of dependencies:
```yaml
foo_task:
  alias: "foo"
  matrix:
    - name: "foo abc"
   ...
```
Many thanks for your advice! New results are so much cleaner:
![cirrus-clean-names](https://user-images.githubusercontent.com/265639/75912888-24043f80-5e0f-11ea-9555-86fd05105a9a.png)
