### ISSUE TITLE
Additional Containers: Add Script configuration option

### ISSUE THREAD

**Issue by rraub** [cirruslabs/cirrus-ci-docs#593]
# Description

for the `additional_containers` section, it would be useful to be able to specify a `script` to run just like the top level tasks.  Some off the shelf containers like postgres don't support configurations via environment variables. 

# Context
Example

```yaml
  container:
    image: mytestimage:latest
    additional_containers:
      - name: postgres
        image: postgres:11.5-alpine
        cpu: 1
        memory: 2G
        port: 5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: databasename
        script:
          - postgres -c 'shared_buffers=512MB' -c 'max_connections=200' -c 'autovacuum=false'
```
# Anything Else
Additionally if there was a way to get at logs for these additional containers that could be helpful.
