### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#595]
# Question

Not sure why, but my build seems to be having container errors: https://cirrus-ci.com/task/5537049126109184

**Comment by fkorotkov** [comment]
Since it's a private repo logs, config file and a bit more description  of the problem will be appreciated.

**Comment by RDIL** [comment]
Okay, I'll email you.

**Comment by RDIL** [comment]
Actually, I'll put it here, why not.  
Log:
```log
npm i -g bundlesize
npm WARN deprecated iltorb@2.4.5: The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
/usr/local/bin/bundlesize -> /usr/local/lib/node_modules/bundlesize/index.js
/usr/local/bin/bundlesize-init -> /usr/local/lib/node_modules/bundlesize/src/init-status.js
/usr/local/bin/bundlesize-pipe -> /usr/local/lib/node_modules/bundlesize/pipe.js

> iltorb@2.4.5 install /usr/local/lib/node_modules/bundlesize/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/13.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/bundlesize/node_modules/iltorb/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/bundlesize/node_modules/iltorb/.node-gyp'
gyp ERR! System Linux 4.19.76+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bundlesize/node_modules/iltorb
gyp ERR! node -v v13.10.1
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@2.4.5 install: `node ./scripts/install.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iltorb@2.4.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Config: 
```yml
test_task:
  container:
    image: node:latest
  env:
    BUNDLESIZE_GITHUB_TOKEN: ENCRYPTED[REDACTED]
    CI_REPO_OWNER: RDIL
    CI_REPO_NAME: REDACTED
    CI_COMMIT_MESSAGE: ${CIRRUS_CHANGE_MESSAGE}
    CI_COMMIT_SHA: ${CIRRUS_CHANGE_IN_REPO}
  use_compute_credits: true
  dependencies_script: npm i -g bundlesize
  script: bundlesize
```
it fails on the installing of the bundlesize CLI script.
