### ISSUE TITLE
Publish dispatch events

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#629]
# Description

Let's post [repository_dispatch](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) event for builds completion. We can populate `payload` with the same content as [Cirrus CI's Webhook](https://cirrus-ci.org/api/#webhooks)'s `data` field.

# Context

Some users want to integrate GitHub actions to run after Cirrus builds finishes. Even though it's possible to hook into check suite's completion:

```yaml
on:
  check_suite:
    type: ['completed']
    
name: Continue after Cirrus CI Complets Successfully
jobs:
  continue:
    name: After Cirrus CI
    if: github.event.check_suite.app.name == 'Cirrus CI' &&  github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Continue	
      run: echo "Hello after Cirrus CI Completed"
```

It's hard to get information about the corresponding Cirrus builds. A user will need to query Cirrus API plus some users reported weirdness in actions behaviour.

**Comment by fkorotkov** [comment]
Cirrus can publish two types of events to be consistent with webhooks: `build-created` and `build-updated`. Then a GH Action will look like this:

```yaml
on:
  repository_dispatch:
    type: ['build-updated']
    
name: Continue after Cirrus CI Complets Successfully
jobs:
  continue:
    name: After Cirrus CI
    if: github.event.client_payload.build.status == 'COMPLETED'
    runs-on: ubuntu-latest
    steps:
    - name: Continue	
      run: echo "Hello after Cirrus CI Completed"
```
