### ISSUE TITLE
Build Matrix based on Environment Variables

### ISSUE THREAD

**Issue by swaldhoer** [cirruslabs/cirrus-ci-docs#635]
# Question

How do I get a build matrix for different values of an environment variable? My build is different for e.g.,
-  ``INCLUDE_FEATRUE_XY=TRUE`` and
- ``INCLUDE_FEATRUE_XY=FALSE``.

This shows for example how it is done on [Travis-CI](https://docs.travis-ci.com/user/build-matrix/#matrix-expansion).

**Comment by RDIL** [comment]
```
task:
  env:
    matrix:
      - VAL: data
      - VAL: data2
```

should do it
