### ISSUE TITLE
Artifact upload/download very slow for 1000+ files

### ISSUE THREAD

**Issue by bdrewery** [cirruslabs/cirrus-ci-docs#637]
# Question

https://cirrus-ci.com/task/4855508010008576
```
always:                                                                                                                        
        bulk_logs_cleanup_script:                                                                                              
                - ( find -x test_bulk/data/logs/bulk ! -name '*.log' ! -name '.poudriere.*' ! -name '*.json' -delete; ) || true
        test_logs_artifacts:
                paths:
                        - "test/*.log"
                        - "test_bulk/data/logs/bulk/**"
                type: text/plain
```
https://api.cirrus-ci.com/v1/task/4855508010008576/logs/test_logs.log

The `test_logs` artifact upload took 4:10 while the rest of the job was just over 6 minutes. 
Downloading the full zip file took several minutes and is only 1.4M zipped and 7.2M unzipped.
In total there are 1688 files and 152 directories.

Is this just an infrastructure/network issue or is it due to the number of files I am uploading? Is there some way I could improve this so it's not nearly doubling the job time? I haven't tried pre-tarring them but given the download time I'm not sure I want to do that either.
