### ISSUE TITLE
Way to clone submodules

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-docs#648]
Right now, Cirrus doesn't seem to clone submodules.  I know this because it can be seen in [this build](https://cirrus-ci.com/task/6039349894578176) which failed because the bulma submodule was not present.

It would be cool if there was either an environment variable (`CIRRUS_CLONE_SUBMODULES`) or just a YAML option (e.g.
```yaml
my_task:
  clone:
    submodules: true
```
).
