### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by Godin** [cirruslabs/cirrus-ci-docs#65]
Given that Cirrus CI agent is written in Go, should be fairly easy to compile it with `GOOS=freebsd GOARCH=amd64`, so that one will be able to use FreeBSD in addition to Windows and Linux images in GCE:

```
gce_instance:
  image_project: freebsd-org-cloud-dev
  image_name: freebsd-11-2-release-amd64
  platform: freebsd
  zone: us-central1-a
  cpu: 8
  memory: 40Gb
  disk: 20

task:
  script: echo OK
```
