### ISSUE TITLE
Failed to unarchive cache, unexpected EOF! error causes re-population on cache hit

### ISSUE THREAD

**Issue by jmagman** [cirruslabs/cirrus-ci-docs#660]
# Expected Behavior

Added caches to .cirrus.yml
```yaml
all_flutter_cache:
    folder: bin/cache/
    fingerprint_script: echo $OS; cat bin/internal/*.version
    populate_script:
      - git fetch origin
      - git fetch origin master # To set FETCH_HEAD, so that "git merge-base" works.
      - flutter precache
      - flutter doctor -v
    reupload_on_changes: false
```

First run should populate bin/cache/ and upload.  Re-run of the same test should have a cache hit, download, and unarchive to the cache directory.

# Real Behavior
Two cache hits and downloads (though different sizes), then a re-population.
```
Downloaded 34Mb.
Cache hit for all_flutter-63d900186d3a60312e13bfde6674e6c916430d346ccad2437a8b19d1c757898c!
Failed to unarchive all_flutter cache because of /tmp/flutter sdk/bin/cache/artifacts/engine/android-arm64-profile/darwin-x64/gen_snapshot: writing file after 157192 bytes (expected 10830404): unexpected EOF! Retrying...
Downloaded 50Mb.
Cache hit for all_flutter-63d900186d3a60312e13bfde6674e6c916430d346ccad2437a8b19d1c757898c!
Failed again to unarchive all_flutter cache because of /tmp/flutter sdk/bin/cache/artifacts/engine/android-x64/flutter.jar: writing file after 789011 bytes (expected 11100217): unexpected EOF!
Treating this failure as a cache miss! Cleaning up /tmp/flutter sdk/bin/cache...
Cache miss for all_flutter-63d900186d3a60312e13bfde6674e6c916430d346ccad2437a8b19d1c757898c! Populating...
git fetch origin
...
```

# Related Info
- [x] Task issue
  - OS: macOS
  - Task name: https://cirrus-ci.com/task/6580763682406400?command=all_flutter#L16
  - all_flutter

Attempted in https://github.com/flutter/flutter/pull/60562.

This isn't specific to macOS, here's on on linux:
https://cirrus-ci.com/task/6173031162707968?command=pub#L70
