### ISSUE TITLE
Can Dockerfile be configured through matrix config?

### ISSUE THREAD

**Issue by ened** [cirruslabs/cirrus-ci-docs#678]
Given I have a `.cirrus.yml` file like so:

```
connected_check_task:
  name: Flutter driver test on Android
  only_if: $CIRRUS_BRANCH == "master" || CIRRUS_PR != ""
  env:
    API_LEVEL: 29
    TARGET: default
    ARCH: x86_64
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 4G
    kvm: true
```

Then when I look at the Cirrus build step for the Dockerfile:
<img width="1426" alt="Screenshot 2020-07-17 at 12 03 42" src="https://user-images.githubusercontent.com/269860/87779959-9b1dfb80-c825-11ea-92ba-d4fff150d4b7.png">

So I would assume the API_LEVEL environment variable is available in Dockerfile like so:

```
# https://github.com/cirruslabs/docker-images-flutter/blob/master/.cirrus.yml
FROM cirrusci/flutter:1.17.5

RUN yes | sdkmanager \
    "platforms;android-$API_LEVEL" \
    "build-tools;29.0.3" \
    "extras;google;m2repository" \
    "extras;android;m2repository" \
    "system-images;android-$API_LEVEL;default;x86_64"

RUN yes | sdkmanager --licenses
```

But it seems not, the docker build fails.

**Comment by fkorotkov** [comment]
I think you can use `docker_arguments` for that:

```yaml
container:
    dockerfile: .ci/Dockerfile
    docker_arguments:
        API_LEVEL: $API_LEVEL
    cpu: 4
    memory: 4G
    kvm: true
```

And add the following to your Dockerfile:

```Dockerfile
ARG API_LEVEL
```

**Comment by ened** [comment]
That is neat, but I think it may not work yet:

```
connected_check_task:
  name: Flutter driver test on Android
  only_if: $CIRRUS_BRANCH == "master" || CIRRUS_PR != ""
  env:
    API_LEVEL: 29
    TARGET: default
    ARCH: x86_64
  container:
    dockerfile: .ci/Dockerfile
    docker_arguments:
      API_LEVEL: $API_LEVEL
      ARCH: $ARCH
      TARGET: $TARGET
    cpu: 4
    memory: 8G
    kvm: true
```

```
ARG API_LEVEL
ARG ARCH
ARG TARGET

# https://github.com/cirruslabs/docker-images-flutter/blob/master/.cirrus.yml
FROM cirrusci/flutter:1.17.5

RUN yes | sdkmanager \
    "platforms;android-$API_LEVEL" \
    "build-tools;29.0.3" \
    "extras;google;m2repository" \
    "extras;android;m2repository"
RUN yes | sdkmanager --licenses
```

At the moment, $API_LEVEL resolves to a empty string.

For reference: https://cirrus-ci.com/task/4728048891199488
