### ISSUE TITLE
How to specify multiple additional_containers

### ISSUE THREAD

**Issue by mattlorey** [cirruslabs/cirrus-ci-docs#69]
Is it possible to specify multiple additional containers?  Every way I try only starts the first.  I've tried:

```
  additional_containers:
    - name: redis
      image: redis:3.2-alpine
      port: 6379
  additional_containers:
    - name: postgres
      image: mdillon/postgis
      port: 5432
```

as well as 
```
  additional_containers:
    - name: redis
      image: redis:3.2-alpine
      port: 6379
    - name: postgres
      image: mdillon/postgis
      port: 5432
```

**Comment by fkorotkov** [comment]
Hey @mattlorey, the second option should work. Do you have an id of the task where you tried it? Or maybe you can share `.cirrus.yml`?

**Comment by fkorotkov** [comment]
You might be missing a label for `mdillon/postgis`

**Comment by mattlorey** [comment]
I added a tag to `mdillon/postgis` to test and that didn't change anything, here is the id: https://cirrus-ci.com/build/6387716866441216 (it's private, but you might be able to see it?)

Here is the relvant part of the `.cirrus.yml`
```
container:
  image: mattlorey/elixir-build:latest
  additional_containers:
    - name: postgres
      image: mdillon/postgis:10-alpine
      port: 5432
      env:
        POSTGRES_USER: db
        POSTGRES_PASSWORD: db
        POSTGRES_DB: db
    - name: redis
      image: redis:3.2-alpine
      port: 6379
```

**Comment by fkorotkov** [comment]
@mattlorey it was an edge case for the parser because it was outside of a task. Sorry about that! It's been fixed now. If you'll push it again `redis` container will work.

**Comment by mattlorey** [comment]
Oh wow, I see it working already!  Thanks for the quick response.

I guess I didn't realize you could specify that in a task, which I only need them in one task so that's good to know!

**Comment by fkorotkov** [comment]
You can even do something like this:

```
container:
  image: mattlorey/elixir-build:latest

unit_tests_task:
  ...

integration_tests_task:
  container:
    additional_containers:
      ...
```

To use `mattlorey/elixir-build:latest` by default and add `additional_containers` for only `integration_tests_task`
