### ISSUE TITLE
MSYS2 need to be updated

### ISSUE THREAD

**Issue by lygstate** [cirruslabs/cirrus-ci-docs#699]
According to
https://www.msys2.org/news/#2020-06-29-new-packages

The msys2's signature is updated

```
windows_msys2_task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 8
    memory: 8G
  env:
    MSYS: winsymlinks:nativestrict
    MSYSTEM: MINGW64
    CHERE_INVOKING: 1
  printenv_script: C:\tools\msys64\usr\bin\bash.exe -lc 'printenv'
  install_script:
    C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm --needed"
    C:\tools\msys64\usr\bin\bash.exe -lc "sh scripts/ci/windows/msys2_install.sh"
  script:
    C:\tools\msys64\usr\bin\bash.exe -lc "sh scripts/ci/windows/msys2_build.sh"


```
Hope updating  cirrusci/windowsservercore:cmake with newest msys2
