### ISSUE TITLE
Environment Variables for Execution Environment

### ISSUE THREAD

**Issue by kimkim19642004** [cirruslabs/cirrus-ci-docs#709]
# Question
I want to write tasks in the following format, is it possible?
```
# Building on Multiple Operating Systems
build_task:
  env:
    matrix:
      # Linux
      - container: image: ubuntu:latest
        LANG: en_US.UTF-8
        CC: gcc
        CXX: g++
        
      # macOS
      - osx_instance: image: catalina-xcode
        LANG: ja_JP.UTF-8
        CC: clang
        CXX: clang++

      # FreeBSD
      - freebsd_instance: image_family: freebsd-12-1
        LANG: fr_FR.UTF-8
        CC: icc
        CXX: icpc
```

**Comment by fkorotkov** [comment]
Yes, you can do:

```yaml
build_task:
  matrix:
    - name: Linux
      contianer:
        image: ubuntu:latest
      env:
        LANG: en_US.UTF-8
        CC: gcc
        CXX: g++
    - name: macOS
      osx_instance: 
        image: catalina-xcode
      env:
        LANG: ja_JP.UTF-8
        CC: clang
        CXX: clang++
      - name: FreeBSD
        freebsd_instance: 
          image_family: freebsd-12-1
        env:
          LANG: fr_FR.UTF-8
          CC: icc
          CXX: icpc
```
