### ISSUE TITLE
Yarn Workspace Caching

### ISSUE THREAD

**Issue by jonstuebe** [cirruslabs/cirrus-ci-docs#718]
# Question

I have a monorepo with yarn workspaces and have run into an interesting issue that I'm not sure how to resolve. I'm running into an issue where I'm caching the top level `node_modules` folder but I can't seem an easy way to cache each package's `node_module` folder as well.

Is there a way to cache multiple folders as part of one cache? Possibly through a glob or something else? If not, do I simply have to create a ton of caches (one per package)?

Thanks!

**Comment by fkorotkov** [comment]
Hey @jonstuebe,

It's an interesting use case and "create a ton of caches (one per package)" definitely not a way to go. Unfortunately right now the caching instruction can only cache a single folder since we need to support caching outside of the working directory and make sure the cache entry is portable by storing relative paths inside the cached archive.

I wonder if specifying `YARN_CACHE_FOLDER` and storing it will solve your issue:

```yaml
env:
  YARN_CACHE_FOLDER: /tmp/yarn-cache
yarn_cache:
  folder: $YARN_CACHE_FOLDER
  fingerprint_script: find . -name "package.json" -exec sha256sum {} \;
  populate_script: yarn install
```

If not then we'll need to add an option to store a list/glob of folders with a restriction to folders inside the working folder.

**Comment by jonstuebe** [comment]
Thanks! I'll give it a try and report back

**Comment by jonstuebe** [comment]
So it kinda helps but it still requires me to do a `yarn install` in each task that depends on that cache as the actual `node_modules` folder's are restored from the cache. And just doing a `yarn install` is taking somewhere around 90 seconds in each task. What would be amazing is if I could do something like this:

```yaml
node_modules_cache:
  folder:
    - node_modules
    - packages/**/node_modules
  fingerprint_script: yarn.lock
  populate_script: yarn install
```

**Comment by fkorotkov** [comment]
Thanks for checking! Created https://github.com/cirruslabs/cirrus-ci-agent/issues/53 to support glob like syntax in the caching instruction:

```yaml
node_modules_cache:
  folder: **/node_modules
  fingerprint_script: find . -name "package.json" -exec sha256sum {} \;
  populate_script: yarn install
```

Either I or @edigaryev will take a look this week. Will update this issue once the agent change is available in production.

**Comment by jonstuebe** [comment]
Out of curiosity why checksum the `package.json` files over fingerprinting the `yarn.lock`? Wouldn't that mean you wouldn't cache sometimes when you should?

**Comment by fkorotkov** [comment]
you are right! fixed it.

**Comment by fkorotkov** [comment]
@jonstuebe the agent got just a new release of the glob support but it's not yet available on Cirrus. You can try to manually test it:

```yaml
enc:
  CIRRUS_AGENT_VERSION: 1.14.0
node_modules_cache:
  folder: **/node_modules
  fingerprint_script: cat yarn.lock
  populate_script: yarn install
```

**Comment by jonstuebe** [comment]
How would I manually test it if it's not available on cirrus yet?

**Comment by fkorotkov** [comment]
BTW seems with Yarn 2 aka berry something like this is possible:

```yaml
node_modules_cache:
  folder: .yarn/cache
  fingerprint_script: cat yarn.lock
install_script: yarn install
```

**Comment by jonstuebe** [comment]
ya I'd love to but we don't use Yarn 2

**Comment by fkorotkov** [comment]
@jonstuebe `CIRRUS_AGENT_VERSION` will override the current default version.

**Comment by jonstuebe** [comment]
Getting this guy:

`Cannot expand cache folder glob '/**/node_modules' that points above the current working directory /tmp/cirrus-ci-build/`

**Comment by fkorotkov** [comment]
Do you have `folder: /**/node_modules` with the prefixed `/`? In this case the agent thinks it's an absolute path.

**Comment by jonstuebe** [comment]
Nope, for some reason it always thinks it's an absolute path. This worked though 😉

```
  env:
    CIRRUS_AGENT_VERSION: 1.14.0
  node_modules_cache:
    folder: "tmp/cirrus-ci-build/**/node_modules"
    fingerprint_script: cat yarn.lock
    populate_script: yarn
```
