### ISSUE TITLE
Ability to interact with docker outside of `docker_builder` task

### ISSUE THREAD

**Issue by mattlorey** [cirruslabs/cirrus-ci-docs#72]
Is it possible to use docker outside of the `docker_builder` task, or specify a customer container for the `docker_builder` task?

I want to push my images to Amazon ECS which requires the AWS cli for authentication, and then also heroku's registry which requires their cli as well.

I was able to install the AWS cli on the `docker_builder` image and push to ECS, and I may be able to get heroku's cli isntalled as well, but I'd rather not have to install that everytime and just use my own image that already has the dependencies.

Here is the relevant parts of my `.cirrus.yml`

```
qa_docker_builder:
  name: QA Build
  depends_on:
  - Compile
  - Lint
  - Test
  env:
    AWS_ACCESS_KEY_ID: ENCRYPTED[...]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[...]
    AWS_DEFAULT_REGION: us-east-2
    AWS_DOCKER_REGISTRY: <...>
    AWS_CLI_VERSION: 1.15.56
    APP_NAME: <...>
  install_awscli_script:
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py --user --no-warn-script-location
    - /root/.local/bin/pip install --no-cache-dir awscli==$AWS_CLI_VERSION
  build_script:
    - $(aws ecr get-login --no-include-email --region us-east-2)
    - docker pull ${AWS_DOCKER_REGISTRY}:latest || true
    - docker build . --cache-from ${AWS_DOCKER_REGISTRY}:latest --build-arg APP_NAME=${APP_NAME} --build-arg APP_VSN=$(grep -m 1 '@app_version' mix.exs | cut -d '"' -f2) --tag ${AWS_DOCKER_REGISTRY}:latest --tag ${AWS_DOCKER_REGISTRY}:$(git rev-parse --short HEAD)
  push_script:
    - docker push ${AWS_DOCKER_REGISTRY}
  # Could try and install heroku's CLI and push to heroku in this task inside the docker_builder container

qa_deploy_task:
  name: QA Deploy
  env:
    HEROKU_API_KEY: ENCRYPTED[...]
    AWS_ACCESS_KEY_ID: ENCRYPTED[...]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[...]
    AWS_DEFAULT_REGION: us-east-2
    AWS_DOCKER_REGISTRY: <...>
    HEROKU_DOCKER_REGISTRY: <...>
    APP_NAME: <...>
    HEROKU_APP: <...>
  depends_on:
    - QA Build
  pull_script:
    - $(aws ecr get-login --no-include-email --region us-east-2)
    # can't user docker here, but heroku and aws cli's are already installed
    - docker pull ${AWS_DOCKER_REGISTRY}:latest
    - docker tag ${AWS_DOCKER_REGISTRY}:latest ${HEROKU_DOCKER_REGISTRY}/web
    - docker tag ${AWS_DOCKER_REGISTRY}:latest ${HEROKU_DOCKER_REGISTRY}/background
  push_script:
    - heroku login
    - heroku container:login
    - docker push ${HEROKU_DOCKER_REGISTRY}/web
    - docker push ${HEROKU_DOCKER_REGISTRY}/background
  deploy_script:
    - heroku container:release web background --app ${HEROKU_APP}
```
