### ISSUE TITLE
Support selectable number of CPUs for docker_builder

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-docs#741]
# Description

The `docker_builder` task should support a selectable number of CPUs.  Right now it's hard-coded to 4.

# Context

The Nix project has some tasks that must use `docker_builder`, even though they can only take advantage of a single CPU.  So we're wasting resources.  Our builds would schedule sooner, and your bills would be lower, if we could reduce the CPU count.

# Anything Else

The task in question:
https://github.com/nix-rust/nix/blob/5729d0f391775c98699f0f92f8df6b7f5f49fc7d/.cirrus.yml#L53

**Comment by RDIL** [comment]
Good idea!  Can't hurt to have faster build times 😄

**Comment by asomers** [comment]
I tried following the instructions in 25346a5 , but they don't work.  My builds failed with a `Failed to start an instance: INVALID_ARGUMENT: Forbidden` error.  Is something about this not allowed for community cluster builds?  Here is the relevant excerpt of my .cirrus.yml:
```yml
task:
  env:
    ...
  matrix:
    ...
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker_builder
    platform: linux
    cpu: 1                          # Since QEMU will only use 1 thread
    memory: 4G
  setup_script:
    ...
```

https://github.com/nix-rust/nix/pull/1392
