### ISSUE TITLE
Option to use Starlark in script instruction

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#748]
# Description

Right now it's possible to use Starlark for configuring tasks (in beta since https://github.com/cirruslabs/cirrus-cli/issues/45). Once the Starlark support is GA we should consider allowing to use Startlark in script instructions. There are two use cases I can see right now:

1. Configure the same cache keys for Windows and Linux #747
2. Use Starlark's builtin `http` functions to send API requests instead of requiring `curl` or `wget` being available.

We can use a hashbang in order to let the [agent](https://github.com/cirruslabs/cirrus-ci-agent) know how to interpret the script. For example:

```yaml
task:
  name: Upload GitHub Relesea
  ...
  upload_script:
    - #!starlark
    - load("cirrus", "http", "fs")
    - http.post(...)
```

Or for the cache entry case:

```yaml
task:
  cache:
    fingerprint_script:
      - #!starlark
      - load("cirrus", "env")
      - println(env.get("FINGERPRINT_KEY"))
```
