### ISSUE TITLE
Feature: Shell-style embedded env. var. substitution

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#75]
I'd like to be able to specify global and task or matrix env. vars, which include other env. vars.  This supports consolidating CI-automation details into a central location.  For example:

```YAML
...snip...
env:
     GOPATH: "/root/go"
     GOSRC: "$GOPATH/src/github.com/some/thing"
     CIRRUS_WORKING_DIR: "$GOSRC"
     SCRIPT_BASE: "$GOSRC/contrib/cirrus"
     PACKER_BASE: "${SCRIPT_BASE}/packer"
...snip...
```

Though since YAML/JSON hash values are un-ordered, this is sometimes challenging to accomplish.  One idea could be to limit iteration by some fixed value, like ``10``.  Do recursive substitution for each key/value up to the limit.  If there are still leftover tokens found in the string, toss an error.

Another simpler approach, would be to require the env-vars to be stored as a list instead.  Then substitution can simply done in-order.  Though this would require a ``.cirrus.yml`` format change, for example:

```YAML
...snip...
env:
     - GOPATH="/root/go"
     - GOSRC="$GOPATH/src/github.com/some/thing"
     - CIRRUS_WORKING_DIR="$GOSRC"
     - SCRIPT_BASE="$GOSRC/contrib/cirrus"
     - PACKER_BASE="${SCRIPT_BASE}/packer"
...snip...
```
