### ISSUE TITLE
Share folder between tasks

### ISSUE THREAD

**Issue by vinferrer** [cirruslabs/cirrus-ci-docs#750]
# Question
hello, Is a way of sharing a folder between all the tasks in a .cirrus.yml?

**Comment by vinferrer** [comment]
My name is Vicente and I am a new user in cirrus CI. I wanted to know if there is a way of sharing a folder or persist a folder between tasks, my main goal is to create a  in one of the tasks conda enviroment and then run tests on it in tasks that would depend on this first task. Let me put the code of my yml file here:
```
makeenv_task:
  Generate_environment_script:
    - conda create -yq --prefix  $PWD/phys2bids_py37 python=3.7
    - source activate $PWD/phys2bids_py37
    - pip install -e ".[test,doc]"


unittest_37_task:
  depends_on:
  - makeenv_task
  Running_unit_tests_script:
    - source activate $PWD/phys2bids_py37
    - sudo apt-get install -y make
    - make unittest
    - mkdir /tmp/cirrus-ci-build/coverage
    - mv /tmp/cirrus-ci-build/.coverage /tmp/cirrus-ci-build/coverage/.coverage.py37
 ````

Would it be possible to maintain $PWD/phys2bids_py37 folder so the unittest_37_task can source the conda enviroment?

Thank you in advance and merry christmas,

**Comment by fkorotkov** [comment]
Hey @vinferrer,

The main way of persisting a folder is to use a [cache instruction](https://cirrus-ci.org/guide/writing-tasks/?h=+cache#cache-instruction). I assume you want to generate once and run a matrix of sub-tasks to test it in several environments?

The trick with a cache instruction will be to use `echo $CIRRUS_BUILD_ID` as `fingerprint_script` in order to make all tasks within a build to use it. In this case your config will look like:

```yaml
makeenv_task:
  environment_cache:
    folder: phys2bids_py37
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - conda create -yq --prefix  $PWD/phys2bids_py37 python=3.7
      - source activate $PWD/phys2bids_py37
      - pip install -e ".[test,doc]"


unittest_37_task:
  depends_on:
  - makeenv_task
  environment_cache:
    folder: phys2bids_py37
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - conda create -yq --prefix  $PWD/phys2bids_py37 python=3.7
      - source activate $PWD/phys2bids_py37
      - pip install -e ".[test,doc]"
  Running_unit_tests_script:
    - source activate $PWD/phys2bids_py37
    - sudo apt-get install -y make
    - make unittest
    - mkdir /tmp/cirrus-ci-build/coverage
    - mv /tmp/cirrus-ci-build/.coverage /tmp/cirrus-ci-build/coverage/.coverage.py37
```

But if your conda environment is too bit then caching might take longer then just generating it in every task.
