### ISSUE TITLE
Share installed enviroment between tasks (windows)

### ISSUE THREAD

**Issue by vinferrer** [cirruslabs/cirrus-ci-docs#758]
# Question

Ask away!
Hi, I have to run several test in my toolbox. Is it possible create a task ``makeenv_37_windows`` that install all the things I need and then divide this in two tasks that would run different kind of tests? At the moment I am installing the same enviroment individually:

````
Integration_39_windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    CIRRUS_SHELL: powershell
  environment_cache:
    folder: shared39
    fingerprint_script: echo 362
    reupload_on_changes: true
    populate_script:
      - choco install make python -y --no-progress; $env:Path += ";c:\python39"; $env:Path += ";c:\python39\Scripts"; refreshenv; echo $env:path
      - pip install --upgrade certifi
      - pip install wheel
      - pip install -e ".[test,doc]"
  Running_integration_script:
    - choco install make -y --no-progress
    - $env:Path += ";c:\python39"; $env:Path += ";c:\python39\Scripts"; refreshenv; echo $env:path
    - make integration

Unittest_39_windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    CIRRUS_SHELL: powershell
  environment_cache:
    folder: shared39
    fingerprint_script: echo 362
    reupload_on_changes: true
    populate_script:
      - choco install make python -y --no-progress; $env:Path += ";c:\python39"; $env:Path += ";c:\python39\Scripts"; refreshenv; echo $env:path
      - pip install --upgrade certifi
      - pip install wheel
      - pip install -e ".[test,doc]"
  Running_integration_script:
    - choco install make -y --no-progress
    - $env:Path += ";c:\python39"; $env:Path += ";c:\python39\Scripts"; refreshenv; echo $env:path
    - make unittest
````

As you can see, All the steps are the same until the last one.
