### ISSUE TITLE
Share cache folder in same job matrix

### ISSUE THREAD

**Issue by vinferrer** [cirruslabs/cirrus-ci-docs#759]
# Question
Hi, I am trying to setup in parallel two conda enviroment folders but i want to store them in the same folder. My thinking is that in the end I wan to create a job that puts together the coverage of all tested python versions in my jobs. How can I achieve this?
````
makeenv_task:
  environment_cache:
    folder: shared
    fingerprint_script: echo ${CIRRUS_BUILD_ID}31
    matrix:
      - name: makeenv_37
        populate_script:
        - conda create -yq --prefix  $PWD/shared/phys2bids_py37 python=3.7
        - source activate $PWD/shared/phys2bids_py37
        - pip install -e '.[test,doc]'
      - name: makeenv_36
        populate_script:
          - conda create -yq --prefix  $PWD/shared/phys2bids_py36 python=3.6
          - source activate $PWD/shared/phys2bids_py36
          - pip install -e '.[test,doc]'
    reupload_on_changes: true

checkenv_task:
  depends_on:
  - makeenv
  environment_cache:
    folder: shared
    fingerprint_script: echo ${CIRRUS_BUILD_ID}31
    reupload_on_changes: true
  check_script:
  - sudo apt-get install -y tree
  - tree $PWD/shared/phys2bids_py36
  - tree $PWD/shared/phys2bids_py37
````
For the moment I am trying this, however the check_task doesn't recieve any cache from makeenv job. Thanks for the help in advance

**Comment by vinferrer** [comment]
If a job can read cache folders from different envs, that could be an option too

**Comment by fkorotkov** [comment]
I think your `makeenv`'s caches are missing `fingerprint_script`s so the cache key is different. If you environment depends only on contents of `setup.py` you can use it as the fingerprint. Will something like that work for you?

```yaml
checkenv_task:
  env:
    matrix:
      PYTHON: 3.6
      PYTHON: 3.7
  environment_cache:
    folder: onda-env
    fingerprint_script: 
      - echo $PYTHON
      - cat setup.py
    populate_script:
      - conda create -yq --prefix  $PWD/conda-env python=$PYTHON
      - source activate $PWD/conda-env
      - pip install -e '.[test,doc]'
   activate_script: source activate $PWD/conda-env
   check_script: ...
```

**Comment by vinferrer** [comment]
Thank you for the help. If you don't mind me asking. my unittest task looks like this:
````
Unittest_task:
  depends_on: 
    - makeenv
  env:
    matrix:
      PYTHON: 3.6
      PYTHON: 3.7
      PYTHON: 3.8
      PYTHON: 3.9
  environment_cache:
    folder: conda-env
    fingerprint_script: 
      - echo $PYTHON
      - cat setup.py
    populate_script:
      - source activate $PWD/conda-env
  Running_unit_tests_script:
    - sudo apt-get install -y make tree
    - source activate $PWD/conda-env
    - make unittest
    - mv $PWD/.coverage /tmp/cirrus-ci-build/coverage
    - tree /tmp/cirrus-ci-build/coverage
  ````
I am doing these tests to upload the results to ``codecov``,  however I wanna combine results of all the python versions and then upload to ``codecov``. How can I do this?
