### ISSUE TITLE
Feature: Separate CI permissions from Github permissions

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-docs#76]
For open-source projects on github, it would be nice to allow a trusted community contributor to utilize cirrus automatically, while still protecting the in-repo. automation machinery.  This could be (adequately) accomplished by way of a 'whitelist' and immutable-path regex 'blacklist'.  For example:

**.cirrus-ci.yml**
```yaml
...snip...
some_task:
    authorized_whitelist:  '.cirrus-ci-whitelist'
    filepath_blacklist: '.cirrus-ci-blacklist'
...snip...
```

**.cirrus-ci-whitelist**
```
joe
bill
bob
```

**.cirrus-ci-blacklist**
```
.*cirrus.*
path/to/ci/.*scripts.*
```

Wherein, a CI job is allowed to run so long as ***both***:
* The PR author's github username appears in the ``authorized_users_filepath`` file in ``$CIRRUS_BASE_BRANCH`` HEAD.
* No commit between ``$CIRRUS_BASE_SHA`` and ``$CIRRUS_CHANGE_IN_REPO``, modifies a file matching a pattern in the ``immutable_patterns`` file (also from ``$CIRRUS_BASE_BRANCH`` HEAD).

It's not perfect security, but would modestly protect the automation machinery, while still allowing whitelist-users to propose changes.  In other-words this would allow granting some permission to run CI jobs, without interacting with the repository access-controls.
