### ISSUE TITLE
Support arbitrary Compute Engine VMs for OSS 

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-docs#794]
Right now [`docker_builder`](https://cirrus-ci.org/guide/docker-builder-vm/) is essentially a VM that [we maintain](https://github.com/cirruslabs/vm-images). But some folks requested features that can be covered by allowing any custom VMs from the users with any number of CPUs/memory. Many issues can be resolved by this, for example:

1. [Run a custom kernel](https://twitter.com/AndresFreundTec/status/1360052571226972161) by @anarazel.
2. OpenBSD Support #311
3. DragonFlyBSD Support #101
4. Support selectable number of CPUs for docker_builder #741
5. Support nested virtualization. https://github.com/cirruslabs/cirrus-ci-docs/discussions/793

Here is an analogue of `docker_builder`:

```yaml
task:
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 16G
    nested_virtualization: false
```

This is basically a stripped version of [`gce_instance`](https://cirrus-ci.org/guide/supported-computing-services/#compute-engine) but for OSS and which can use any public compute engine VM.
