### ISSUE TITLE
pipe matrix

### ISSUE THREAD

**Issue by achow101** [cirruslabs/cirrus-ci-docs#802]
The pipe feature is mentioned as a way to execute each instruction in separate docker containers. However, unlike with normal tasks, it seems to be incompatible with matrix expansion. It would be useful to me to be able to use pipe within matrix, or matrix within pipe.

For example, in one of my projects, I have a task that prebuilds some tools which are then used in another matrix-expanded task. However I routinely have issues with getting those prebuilt tools into the tasks. With pipe and matrix, I could have the first step do the prebuild, then the next step be the matrix tasks.

The config that I would like would look like:

```yaml
pipe:
  steps:
    - image: build-image
      build_script: script.sh
    - image: test-image
      test_script: test.sh
      matrix:
      - env:
        VAR1: A
      - env:
        VAR2: B
      - env:
        VAR2: C
```

This would effectively expand into:

```yaml
pipe:
  steps:
    - image: build-image
      build_script: script.sh
    - image: test-image
      test_script: test.sh
      env:
        VAR1: A

pipe:
  steps:
    - image: build-image
      build_script: script.sh
    - image: test-image
      test_script: test.sh
      env:
        VAR1: B

pipe:
  steps:
    - image: build-image
      build_script: script.sh
    - image: test-image
      test_script: test.sh
      env:
        VAR1: C
```

But with the first step being shared across all of the pipes as it is a shared prebuild that they can all use. The working directory from that first step would be copied to all of the expanded second steps.

**Comment by fkorotkov** [comment]
It should be working now. Not that `env` should be directly on a `pipe`:

```yaml
pipe:
  matrix:
    - env:
        VAR1: A
    - env:
        VAR2: B
    - env:
        VAR2: C
  steps:
    - image: build-image
      build_script: script.sh
    - image: test-image
      test_script: test.sh
```
