### ISSUE TITLE
Support multiple port mappings on additional_containers

### ISSUE THREAD

**Issue by malena-ebert-sonarsource** [cirruslabs/cirrus-ci-docs#810]
# Description

It should be possible to map multiple ports of a sidecar container.

# Context

During a task, we have the requirement to access the container by ssh and expose the internal service by http.

# Anything Else
```
container:
  image: debian
  additional_containers:
    - name: gitlab
      image: gitlab:latest
      ports:
        - 8080:80
        - 2222:22
      cpu: 1.0
      memory: 5Gb
```

**Comment by fkorotkov** [comment]
Hey @malena-ebert-sonarsource,

We are about to switch our implantation of the config parser from Kotlin to [the one written in Go](https://github.com/cirruslabs/cirrus-cli/tree/master/pkg/parser). As you know we've been running a comparisment of the parsers in the background for the last couple of months and for the past couple of days we haven't seen any reports of the differences in the parsing results.

How urgent is this feature for you? If everything will go smoothly then we'll switch to the new parser next week and then we can add this feature in just one place. Will that timeline work for you?

FYI be aware of the caveats of using port mapping. I've documented it in #811. If the following config will work for you

```yaml
container:
  image: debian
  additional_containers:
    - name: gitlab
      image: gitlab:latest
      ports:
        - 80
        - 22
      cpu: 1.0
      memory: 5Gb
```

Please consider it instead.
