### ISSUE TITLE
Support tasks using Google Deployment Manager

### ISSUE THREAD

**Issue by TurboTurtle** [cirruslabs/cirrus-ci-docs#870]
# Description

I would like to be able to use Google Deployment Manager in conjunction with Cirrus tasks, much like how we're able to use single GCE instances today.

A rough example of what I see this looking like would be:

```
example_task:
    name: "Example Cluster Task"
    gcp_deployment:
        config: my_gcp_config.yml  # this would be a file that lives in my repo with cirrus.yml
    setup_script: <some prep work that gets run on all instances>
    main_script: run_tests.sh
        only_on: <some way to restrict this script to only execute on a specific instance. Maybe through tags or labels?>
```

At the end of the task, Cirrus would then remove any of the GCE resources created by the deployment. Ideally, Cirrus env vars could be used in `my_gcp_config.yml` - though of course validation of the config itself would be on the developer and not on Cirrus in any way.

# Context

This would allow us to do more complex scenario testing - e.g. testing against clusters or otherwise multiple connected VMs with a known configuration. This would allow developers to test their project against say a temporary OpenStack environment that again has a known and predictable configuration without having to consistently maintain an actual OpenStack cluster for testing purposes.

# Anything Else

...
