### ISSUE TITLE
show validate output at cirrus-ci.com

### ISSUE THREAD

**Issue by muellerbe** [cirruslabs/cirrus-ci-docs#882]
# Description

show validate output at cirrus-ci.com

# Context

I miss configured .cirrus.yml like this

```
...
build_task:
  pip_cache:...
  pip_script:...
...
```
and cirrus-ci.com show only "Errored"

there is a validate in cirrus cli, and this outputs

```
Error: parsing error: task 'build' cache and script instructions have identical name
```

I love to see this output at cirrus-ci.com

# Anything Else

...

**Comment by edigaryev** [comment]
@fkorotkov beat me to it 😅

It should be working now.

**Comment by fkorotkov** [comment]
Let's maybe make parser to output a rich error to highlight an instruction with a duplicated name. 🤔

**Comment by muellerbe** [comment]
successfully tested
https://github.com/osism/openstack-ironic-ipa-images/pull/2
https://cirrus-ci.com/build/5895609874907136

```
build_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: python3 -m pip install --upgrade setuptools wheel

  pip_script:
    - pip install --upgrade pip
```
