### ISSUE TITLE
freebsd_instance ignores additional parameters

### ISSUE THREAD

**Issue by trombik** [cirruslabs/cirrus-ci-docs#911]
## Expected Behavior

the following YAML should run a FreeBSD instance with 80 GB disk.

```yaml
freebsd_instance:
  image_family: freebsd-13-0
  disk: 80
```

## Real Behavior

with `freebsd_instance`, `disk` parameter is ignored, and the size of the disk is the default.

# Related Info

`docs/guide/FreeBSD.md` states:

> "Under the Hood" Under the hood, a basic integration with Google Compute Engine is used and freebsd_instance is a syntactic sugar for the following compute_engine_instance configuration

however, it is not very clear (to me) that you cannot override the defaults with `freebsd_instance`.

possible solutions:

document that `freebsd_instance` cannot override the defaults in the doc. leave the implementation as-is.

or, fix the implementation so that one can modify the defaults by merging parameters in `freebsd_instance`.

my workaround is:

```yaml
compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-13-0
  platform: freebsd
  cpu: 4
  memory: 8
  disk: 80
```
This is a (tick one of the following):

- [x] Website issue
  - Link to page: https://cirrus-ci.org/guide/FreeBSD/
- [x] Task issue
  - OS: FreeBSD
  - Task name: N/A
  - Script/cache name (if applies): N/A
