### ISSUE TITLE
Use additional binary

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-docs#95]
Hello!

I have config for Ruby testing with:

```yaml
test_task:
  container:
    matrix:
      image: ruby:2.5
      image: ruby:2.4
```

And I want to run `yarn` inside tests. How can I do this? `additional_containers`? `apt install`?

Thanks.
