### ISSUE TITLE
Provide compute platform and region as CIRRUS_* variables.

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-docs#951]
Most cloud providers price have cheap or free intra region traffic, more expensive inter-region traffic and even more expensive traffic to other cloud providers.  Containers will often, as e.g. the case with google's artifact registry, be in a region. 

To minimize costs it'd be useful to change the the reference of a docker image to the provider and region a container runs in. Having e.g. CIRRUS_REGION, CIRRUS_MULTI_REGION could allow specifying a container reference like

```yaml
task:
  ...
  container:
    image: ${CIRRUS_MULTI_REGION}-docker.pkg.dev/${GCP_PROJECT}/${GCP_REPO}/my-beautiful-container:tag
```
when mirroring images across the three [multi-regions](https://cloud.google.com/artifact-registry/docs/repo-locations#location-mr) and it could work similarly if one used "plain" regions.

It's a bit less obvious (and not as crucial, given that it can be inferred from the container arch) how to make the same `image: ` work for both gcp and aws, given the restrictions of the yaml format. But it still seems useful to provide the compute provider as a CIRRUS_ variable. I haven't tried yet, but if variable references themselves interpolate variables, it could actually be doable using something like:

```yaml
  env: 
    CONTAINER_REPO_AWS: https://${AWS_ACCOUNT}.dkr.ecr.${CIRRUS_REGIONS}.amazonaws.com
    CONTAINER_REPO_GCP: ${CIRRUS_MULTI_REGION}-docker.pkg.dev/${GCP_PROJECT}/${REPO_NAME}
  container:
    image: ${CONTAINER_REPO_${CIRRUS_PROVIDER}}/my-beautiful-container:tag
```
