### ISSUE TITLE
Cirrus CI not merging YAML maps on anchor usage (but failing instead)

### ISSUE THREAD

**Issue by abravalheri** [cirruslabs/cirrus-ci-docs#980]
Hello, and thanks again for the great work.

Recently I was trying to simplify my CI configuration and I was surprised when I found the following error message:

> Error while parsing tasks: INVALID_ARGUMENT: parsing error: task 'test (Linux - Anaconda)' has two script instructions with an identical name 'install_tools'!

This seems to be related to the fact that is was using a YAML "merge" operation, but defining an override for the `install_tools_script` key.

My [configuration file](https://github.com/pyscaffold/ci-tester/blob/77a1cb94c803da5c17322e01d565fd86275b2f6f/.cirrus.yml) looks like the following:

```yaml
.task_template: &task-template
  install_tools_script:
    - pip install --upgrade pip tox pipx
  # ...

.test_task_template: &test-task-template
  <<: *task-template
  # ...

conda_task:
  <<: *test-task-template
  install_tools_script: # Overwrite template
    - conda install -y -c conda-forge pip tox pipx
```

This is just a simplification focusing on the relevant parts, the complete file can be found in:
- https://github.com/pyscaffold/ci-tester/blob/77a1cb94c803da5c17322e01d565fd86275b2f6f/.cirrus.yml
- Build URL with error message: https://cirrus-ci.com/build/5993587279134720

## Expected Behavior

Cirrus CI should have merged the YAML maps and overridden the value of the `install_tools_script` with the one that was defined later in the script. There should be no error about duplicated keys.

Please note that this YAML behaviour is well known (and expected to be reliable upon):

- https://yaml.org/type/merge.html
- https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
- https://ktomk.github.io/writing/yaml-anchor-alias-and-merge-key.html
- https://www.linode.com/docs/guides/yaml-anchors-aliases-overrides-extensions/
- https://blog.daemonl.com/2016/02/yaml.html

## Real Behavior

What ended up happening was an error in Cirrus CI web interface:

> Error while parsing tasks: INVALID_ARGUMENT: parsing error: task 'test (Linux - Anaconda)' has two script instructions with an identical name 'install_tools'!

# Related Info

This might be related to: https://github.com/cirruslabs/cirrus-ci-docs/issues/413

This is a (tick one of the following):

- [ ] Website issue
  - Link to page:
- [x] Task issue
  - OS: Docker
  - Task name: `conda_task`
  - Script/cache name (if applies): `install_tools_script`
