### ISSUE TITLE
📝 Document `/tmp` for additional containers (and make `port` optional)

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-docs#992]
# Description

Currently the Cirrus CI documentation contains the following statement regarding `additional_containers`:

> Each additional container should have a unique name and specify at least Docker image and port that this container exposes.

Additionally, under behavioral environment variables, it documents the `CIRRUS_VOLUME` variable as defaulting to `/tmp` and having the following effect:

> Defines a path for a temporary volume to be mounted into instances running in a Kubernetes cluster. This volume is mounted into all additional containers and is persisted between steps of a pipe.

This `/tmp` volume is useful for inter-container communication, and in some use cases makes the use of a `port` unnecessary. It would be nice if:
* The `/tmp` volume were documented more thoroughly in the "Additional Containers" section of the docs
* The `port` key was no longer a required key in `additional_containers` objects

# Context

I use `additional_containers` to run Docker Builds on GKE (similar [to this example](https://cirrus-ci.org/guide/docker-builds-on-kubernetes/)), but rather than exposing the Docker daemon through a `port`, I create a shared Unix socket in the `/tmp` volume:
```yaml
task:  
  gke_container:
    image: *dockerClientImage
    cpu: 1
    memory: 512Mb
    additional_containers:
      - name: docker
        image: docker:20.10.14-dind
        cpu: 1
        memory: 5Gb
        env:
          DOCKER_HOST: unix:///tmp/docker.sock
        privileged: true
        # Cirrus CI requires us to give a `port` field, even though we don't use it
        port: 63029
  env:
    DOCKER_HOST: unix:///tmp/docker.sock
  version_script: docker version
```

What's great about this approach is that with minimal configuration (i) it avoids the need to disable TLS verification for the daemon or have complicated shared certificates and (ii) avoids worries about potentially exposing a Docker daemon on the pod (which maybe is a totally unfounded concern).

The only thing I don't like about this approach is the need for a `port` field, which I populate with a random number, since it's unused
